<a href="https://colab.research.google.com/github/aletbm/Trabajo_Remunerado-DATA4CCION/blob/main/notebooks/Databases_DAT4CCION.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🌐 International Labour Organization (ILO)

La **Organización Internacional del Trabajo (OIT)** es una agencia especializada de las Naciones Unidas
fundada en 1919. Es la única agencia de la ONU con estructura tripartita: gobiernos, empleadores y
trabajadores tienen representación y voz en sus decisiones.

## Misión
Promover el trabajo decente y productivo en condiciones de libertad, equidad, seguridad y dignidad humana.

## Relevancia para este análisis
La OIT es la fuente de referencia global para estadísticas laborales. Sus datos alimentan directamente
los indicadores de los Objetivos de Desarrollo Sostenible (ODS) relacionados con trabajo, entre ellos:

| ODS | Indicador |
|-----|-----------|
| 5.5.2 | Proporción de mujeres en puestos directivos |
| 8.3.1 | Proporción de empleo informal por sexo |
| 8.5.1 | Ingresos medios por hora por sexo |
| 8.5.2 | Tasa de desempleo por sexo y edad |
| 8.6.1 | Proporción de jóvenes NEET por sexo |

## Fuente de datos
Los datos utilizados en este notebook provienen de **ILOSTAT**, la base de datos estadísticos de la OIT,
accesible via API en `https://rshiny.ilo.org/dataexplorer01/`.

> 📎 Sitio oficial: [ilo.org](https://www.ilo.org) | Datos: [ilostat.ilo.org](https://ilostat.ilo.org)

In [211]:
# @title
import pandas as pd
import requests
from io import StringIO

def read_csv(url):
    headers = {"User-Agent": "Mozilla/5.0"}
    response = requests.get(url, headers=headers)
    response.raise_for_status()

    df = pd.read_csv(StringIO(response.text))
    return df

## Labour force by sex, age and education (thousands)[Annual]

**Information on dataset**

With the aim of promoting international comparability, statistics presented on [ILOSTAT](https://ilostat.ilo.org/data/) are based on standard international definitions wherever feasible and may differ from official national figures. This series is based on the 13th ICLS definitions. For time series comparability, it includes countries that have implemented the 19th ICLS standards, for which data are also available in the Work Statistics -- 19th ICLS (WORK) database. The labour force is the sum of all persons of working age who are employed and those who are unemployed. Data disaggregated by level of education are provided on the highest level of education completed, classified according to the International Standard Classification of Education (ISCED). Data may have been regrouped from national classifications, which may not be strictly compatible with ISCED. For more information, refer to [the Education and Mismatch Indicators (EMI) database description](https://ilostat.ilo.org/methods/concepts-and-definitions/description-education-and-mismatch-indicators/).

+ Subject: Labour force
+ Database: Education and Mismatch Indicators (EMI)¿
+ Id: EAP_TEAP_SEX_AGE_EDU_NB_A
+ Time period: 1970 - 2025
+ Last updated: 19/03/2026 17:45:18
+ Number of records: 1450007

In [212]:
url = "https://rplumber.ilo.org/data/indicator?id=EAP_TEAP_SEX_AGE_EDU_NB_A&type=label&format=.csv"

df = read_csv(url)
df.head()

/tmp/ipykernel_159/1301434483.py:11: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(StringIO(response.text))

,ref_area.label,source.label,indicator.label,sex.label,classif1.label,classif2.label,time,obs_value,obs_status.label,note_classif.label,note_indicator.label,note_source.label
0,Aruba,LFS - Labour Force Survey,"Labour force by sex, age and education (thousa...",Total,"Age (Youth, adults): 15+",Education (Aggregate levels): Total,1994,38.42,NaN,NaN,NaN,NaN
1,Aruba,LFS - Labour Force Survey,"Labour force by sex, age and education (thousa...",Total,"Age (Youth, adults): 15+",Education (Aggregate levels): Basic,1994,31.00,NaN,NaN,NaN,NaN
2,Aruba,LFS - Labour Force Survey,"Labour force by sex, age and education (thousa...",Total,"Age (Youth, adults): 15+",Education (Aggregate levels): Intermediate,1994,1.42,NaN,NaN,NaN,NaN
3,Aruba,LFS - Labour Force Survey,"Labour force by sex, age and education (thousa...",Total,"Age (Youth, adults): 15+",Education (Aggregate levels): Advanced,1994,5.97,NaN,NaN,NaN,NaN
4,Aruba,LFS - Labour Force Survey,"Labour force by sex, age and education (thousa...",Total,"Age (Youth, adults): 15+",Education (Aggregate levels): Level not stated,1994,0.03,NaN,NaN,NaN,NaN

In [213]:
df["ref_area.label"].unique()

array(['Aruba', 'Afghanistan', 'Angola', 'Anguilla', 'Albania',
       'Netherlands Antilles', 'United Arab Emirates', 'Argentina',
       'Armenia', 'Antigua and Barbuda', 'Australia', 'Austria',
       'Azerbaijan', 'Burundi', 'Belgium', 'Benin', 'Burkina Faso',
       'Bangladesh', 'Bulgaria', 'Bahrain', 'Bahamas',
       'Bosnia and Herzegovina', 'Belarus', 'Belize', 'Bermuda',
       'Bolivia (Plurinational State of)', 'Brazil', 'Barbados',
       'Brunei Darussalam', 'Bhutan', 'Botswana', 'Switzerland', 'Chile',
       'China', "Côte d'Ivoire", 'Cameroon',
       'Congo, Democratic Republic of the', 'Congo', 'Cook Islands',
       'Colombia', 'Comoros', 'Cabo Verde', 'Costa Rica', 'Cuba',
       'Curaçao', 'Cayman Islands', 'Germany', 'Djibouti', 'Dominica',
       'Denmark', 'Dominican Republic', 'Algeria', 'Ecuador', 'Egypt',
       'Spain', 'Estonia', 'Ethiopia', 'Finland', 'Fiji',
       'Falkland Islands, Malvinas', 'France',
       'Micronesia (Federated States of)',
       'United Kingdom of Great Britain and Northern Ireland', 'Georgia',
       'Ghana', 'Guinea', 'Guadeloupe', 'Gambia', 'Guinea-Bissau',
       'Greece', 'Grenada', 'Greenland', 'Guatemala', 'French Guiana',
       'Guyana', 'Hong Kong, China', 'Honduras', 'Croatia', 'Haiti',
       'Hungary', 'India', 'Ireland', 'Iran (Islamic Republic of)',
       'Iraq', 'Iceland', 'Israel', 'Italy', 'Jamaica', 'Jordan', 'Japan',
       'Kazakhstan', 'Kenya', 'Kyrgyzstan', 'Kiribati',
       'Saint Kitts and Nevis', 'Republic of Korea', 'Kosovo', 'Kuwait',
       "Lao People's Democratic Republic", 'Lebanon', 'Liberia',
       'Saint Lucia', 'Sri Lanka', 'Lesotho', 'Lithuania', 'Luxembourg',
       'Latvia', 'Macao, China', 'Morocco', 'Monaco',
       'Republic of Moldova', 'Madagascar', 'Maldives', 'Mexico',
       'Marshall Islands', 'North Macedonia', 'Mali', 'Malta', 'Myanmar',
       'Montenegro', 'Mongolia', 'Mozambique', 'Mauritania', 'Montserrat',
       'Martinique', 'Mauritius', 'Malawi', 'Malaysia', 'Namibia',
       'New Caledonia', 'Niger', 'Nicaragua', 'Niue', 'Netherlands',
       'Norway', 'Nepal', 'Nauru', 'New Zealand', 'Oman', 'Pakistan',
       'Panama', 'Peru', 'Philippines', 'Palau', 'Papua New Guinea',
       'Poland', 'Puerto Rico', 'Portugal', 'Paraguay',
       'Palestine (State of)', 'French Polynesia', 'Qatar', 'Réunion',
       'Romania', 'Russian Federation', 'Rwanda', 'Sudan', 'Senegal',
       'Singapore', 'Solomon Islands', 'Sierra Leone', 'El Salvador',
       'San Marino', 'Somalia', 'Serbia', 'South Sudan',
       'Sao Tome and Principe', 'Suriname', 'Slovakia', 'Slovenia',
       'Sweden', 'Eswatini', 'Seychelles', 'Chad', 'Togo', 'Thailand',
       'Tajikistan', 'Tokelau', 'Timor-Leste', 'Tonga',
       'Trinidad and Tobago', 'Tunisia', 'Türkiye', 'Tuvalu',
       'Taiwan, China', 'Tanzania, United Republic of', 'Uganda',
       'Ukraine', 'Uruguay', 'Uzbekistan',
       'Saint Vincent and the Grenadines',
       'Venezuela (Bolivarian Republic of)', 'Viet Nam', 'Vanuatu',
       'Wallis and Futuna', 'Samoa', 'Yemen', 'South Africa', 'Zambia',
       'Zimbabwe'], dtype=object)

In [214]:
latam_countries = [
    'Argentina', 'Bolivia (Plurinational State of)', 'Brazil', 'Chile',
    'Colombia', 'Costa Rica', 'Cuba', 'Dominican Republic', 'Ecuador',
    'El Salvador', 'Guatemala', 'Haiti', 'Honduras', 'Jamaica', 'Mexico',
    'Nicaragua', 'Panama', 'Paraguay', 'Peru', 'Puerto Rico', 'Trinidad and Tobago',
    'Uruguay', 'Venezuela (Bolivarian Republic of)'
]

In [215]:
df[(df["ref_area.label"] == "Argentina") &
   (df["classif1.label"] == "Age (Youth, adults): 15+") &
   (df["classif2.label"] == "Education (Aggregate levels): Less than basic")
  ].head(3)

,ref_area.label,source.label,indicator.label,sex.label,classif1.label,classif2.label,time,obs_value,obs_status.label,note_classif.label,note_indicator.label,note_source.label
30364,Argentina,"LFS - Permanent Household Survey, Urban","Labour force by sex, age and education (thousa...",Total,"Age (Youth, adults): 15+",Education (Aggregate levels): Less than basic,2024,323.723,NaN,NaN,NaN,Repository: ILO-STATISTICS - Micro data proces...
30388,Argentina,"LFS - Permanent Household Survey, Urban","Labour force by sex, age and education (thousa...",Male,"Age (Youth, adults): 15+",Education (Aggregate levels): Less than basic,2024,214.527,NaN,NaN,NaN,Repository: ILO-STATISTICS - Micro data proces...
30412,Argentina,"LFS - Permanent Household Survey, Urban","Labour force by sex, age and education (thousa...",Female,"Age (Youth, adults): 15+",Education (Aggregate levels): Less than basic,2024,109.196,NaN,NaN,NaN,Repository: ILO-STATISTICS - Micro data proces...

In [216]:
from tabulate import tabulate

def summarize_by_country(df, countries, country_col='ref_area.label', time_col='time'):
    rows = []
    for country in countries:
        aux = df[df[country_col] == country]
        rows.append([country, f"{len(aux):,}", aux[time_col].min(), aux[time_col].max()])
    print(tabulate(rows, headers=["País", "Registros", "Desde", "Hasta"], tablefmt="pretty"))

summarize_by_country(df, latam_countries)

+------------------------------------+-----------+-------+-------+
|                País                | Registros | Desde | Hasta |
+------------------------------------+-----------+-------+-------+
|             Argentina              |  14,371   | 2002  | 2024  |
|  Bolivia (Plurinational State of)  |  21,956   | 1991  | 2024  |
|               Brazil               |  23,386   | 1989  | 2025  |
|               Chile                |  16,790   | 1990  | 2025  |
|              Colombia              |  16,198   | 1996  | 2025  |
|             Costa Rica             |  19,148   | 1991  | 2025  |
|                Cuba                |   3,378   | 2002  | 2012  |
|         Dominican Republic         |  19,524   | 1993  | 2025  |
|              Ecuador               |  17,742   | 2000  | 2025  |
|            El Salvador             |  11,218   | 1996  | 2024  |
|             Guatemala              |  11,758   | 2002  | 2024  |
|               Haiti                |   1,038   | 2003  | 2012  |
|              Honduras              |  14,944   | 2005  | 2025  |
|              Jamaica               |  11,268   | 2008  | 2023  |
|               Mexico               |  18,173   | 1995  | 2024  |
|             Nicaragua              |   3,327   | 1995  | 2014  |
|               Panama               |   9,479   | 1982  | 2024  |
|              Paraguay              |  12,942   | 1998  | 2017  |
|                Peru                |  11,884   | 1995  | 2025  |
|            Puerto Rico             |   1,536   | 2015  | 2020  |
|        Trinidad and Tobago         |   3,805   | 1991  | 2024  |
|              Uruguay               |  16,951   | 1998  | 2024  |
| Venezuela (Bolivarian Republic of) |   6,744   | 2005  | 2017  |
+------------------------------------+-----------+-------+-------+

## Working-age population by sex, education and labour market status (thousands) [Annual]

**Information on dataset**

With the aim of promoting international comparability, statistics presented on [ILOSTAT](https://www.google.com/url?q=https%3A%2F%2Filostat.ilo.org%2Fdata%2F) are based on standard international definitions wherever feasible and may differ from official national figures. This series is based on the 13th ICLS definitions. For time series comparability, it includes countries that have implemented the 19th ICLS standards, for which data are also available in the Work Statistics -- 19th ICLS (WORK) database. The working-age population is commonly defined as persons aged 15 years and older, but this varies from country to country. Data disaggregated by level of education are provided on the highest level of education completed, classified according to the International Standard Classification of Education (ISCED). Data may have been regrouped from national classifications, which may not be strictly compatible with ISCED. For more information, refer to the [Education and Mismatch Indicators (EMI) database description](https://ilostat.ilo.org/methods/concepts-and-definitions/description-education-and-mismatch-indicators/).

* Subject: Population
* Database: Education and Mismatch Indicators (EMI)
* Id: POP_XWAP_SEX_EDU_LMS_NB_A
* Time period: 1970 - 2025
* Last updated: 19/03/2026 17:45:18
* Number of records: 323564

In [217]:
url = "https://rplumber.ilo.org/data/indicator?id=POP_XWAP_SEX_EDU_LMS_NB_A&type=label&format=.csv"

df2 = read_csv(url)
df2.head()

,ref_area.label,source.label,indicator.label,sex.label,classif1.label,classif2.label,time,obs_value,obs_status.label,note_classif.label,note_indicator.label,note_source.label
0,Afghanistan,LFS - Labour Force Survey,"Working-age population by sex, education and l...",Total,Education (Aggregate levels): Total,Labour market status: Total,2021,16372.131,NaN,NaN,NaN,Repository: ILO-STATISTICS - Micro data proces...
1,Afghanistan,LFS - Labour Force Survey,"Working-age population by sex, education and l...",Total,Education (Aggregate levels): Total,Labour market status: Employed,2021,7679.474,NaN,NaN,NaN,Repository: ILO-STATISTICS - Micro data proces...
2,Afghanistan,LFS - Labour Force Survey,"Working-age population by sex, education and l...",Total,Education (Aggregate levels): Total,Labour market status: Unemployed,2021,462.411,NaN,NaN,NaN,Repository: ILO-STATISTICS - Micro data proces...
3,Afghanistan,LFS - Labour Force Survey,"Working-age population by sex, education and l...",Total,Education (Aggregate levels): Total,Labour market status: Outside the labour force,2021,8230.246,NaN,NaN,NaN,Repository: ILO-STATISTICS - Micro data proces...
4,Afghanistan,LFS - Labour Force Survey,"Working-age population by sex, education and l...",Total,Education (Aggregate levels): Less than basic,Labour market status: Total,2021,11066.917,NaN,NaN,NaN,Repository: ILO-STATISTICS - Micro data proces...

In [218]:
summarize_by_country(df2, latam_countries)

+------------------------------------+-----------+-------+-------+
|                País                | Registros | Desde | Hasta |
+------------------------------------+-----------+-------+-------+
|             Argentina              |   3,240   | 2004  | 2024  |
|  Bolivia (Plurinational State of)  |   5,550   | 1991  | 2024  |
|               Brazil               |   5,700   | 1989  | 2025  |
|               Chile                |   4,224   | 1998  | 2025  |
|              Colombia              |   3,876   | 2002  | 2025  |
|             Costa Rica             |   4,803   | 2001  | 2025  |
|                Cuba                |    300    | 2002  | 2012  |
|         Dominican Republic         |   4,980   | 2000  | 2025  |
|              Ecuador               |   4,350   | 2000  | 2025  |
|            El Salvador             |   2,781   | 2010  | 2024  |
|             Guatemala              |   3,012   | 2002  | 2024  |
|               Haiti                |    273    | 2003  | 2012  |
|              Honduras              |   3,795   | 2005  | 2025  |
|              Jamaica               |   2,829   | 2008  | 2023  |
|               Mexico               |     0     |  nan  |  nan  |
|             Nicaragua              |    762    | 2001  | 2014  |
|               Panama               |   2,103   | 1997  | 2024  |
|              Paraguay              |   3,255   | 1998  | 2017  |
|                Peru                |   2,934   | 1997  | 2025  |
|            Puerto Rico             |    384    | 2015  | 2020  |
|        Trinidad and Tobago         |    885    | 2010  | 2024  |
|              Uruguay               |   4,272   | 1998  | 2024  |
| Venezuela (Bolivarian Republic of) |   1,704   | 2005  | 2017  |
+------------------------------------+-----------+-------+-------+

## Employment by sex and occupation - ISCO level 2 (thousands) [Annual]

**Information on dataset**

With the aim of promoting international comparability, statistics presented on ILOSTAT are based on standard international definitions wherever feasible and may differ from official national figures. This series is based on the 13th ICLS definitions. For time series comparability, it includes countries that have implemented the 19th ICLS standards, for which data are also available in the Work Statistics -- 19th ICLS (WORK) database. The employed comprise all persons of working age who, during a specified brief period, were in one of the following categories: a) paid employment (whether at work or with a job but not at work); or b) self-employment (whether at work or with an enterprise but not at work). For more information, refer to the [Labour Force Statistics (LFS and STLFS) database description](https://ilostat.ilo.org/methods/concepts-and-definitions/description-labour-force-statistics/).

+ Subject: Employment
+ Database: Labour Force Statistics (LFS)
+ Id: EMP_TEMP_SEX_OC2_NB_A
+ Time period: 1991 - 2025
+ Last updated: 14/03/2026 21:49:42
+ Number of records: 180607

In [219]:
url = "https://rplumber.ilo.org/data/indicator?id=EMP_TEMP_SEX_OC2_NB_A&type=label&format=.csv"

df3 = read_csv(url)
df3.head()

/tmp/ipykernel_159/1301434483.py:11: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(StringIO(response.text))

,ref_area.label,source.label,indicator.label,sex.label,classif1.label,time,obs_value,obs_status.label,note_classif.label,note_indicator.label,note_source.label
0,Afghanistan,LFS - Labour Force Survey,Employment by sex and occupation - ISCO level ...,Total,"Occupation (ISCO-08), 2 digit level: Total",2021,7679.474,NaN,NaN,NaN,Repository: ILO-STATISTICS - Micro data proces...
1,Afghanistan,LFS - Labour Force Survey,Employment by sex and occupation - ISCO level ...,Total,"Occupation (ISCO-08), 2 digit level: 02 - Non-...",2021,209.728,NaN,NaN,NaN,Repository: ILO-STATISTICS - Micro data proces...
2,Afghanistan,LFS - Labour Force Survey,Employment by sex and occupation - ISCO level ...,Total,"Occupation (ISCO-08), 2 digit level: 11 - Chie...",2021,7.876,Unreliable,NaN,NaN,Repository: ILO-STATISTICS - Micro data proces...
3,Afghanistan,LFS - Labour Force Survey,Employment by sex and occupation - ISCO level ...,Total,"Occupation (ISCO-08), 2 digit level: 12 - Admi...",2021,89.945,NaN,NaN,NaN,Repository: ILO-STATISTICS - Micro data proces...
4,Afghanistan,LFS - Labour Force Survey,Employment by sex and occupation - ISCO level ...,Total,"Occupation (ISCO-08), 2 digit level: 13 - Prod...",2021,23.102,NaN,NaN,NaN,Repository: ILO-STATISTICS - Micro data proces...

In [220]:
summarize_by_country(df3, latam_countries)

+------------------------------------+-----------+-------+-------+
|                País                | Registros | Desde | Hasta |
+------------------------------------+-----------+-------+-------+
|             Argentina              |   2,142   | 2004  | 2024  |
|  Bolivia (Plurinational State of)  |   2,907   | 1991  | 2024  |
|               Brazil               |   2,628   | 2002  | 2025  |
|               Chile                |     0     |  nan  |  nan  |
|              Colombia              |   2,877   | 2002  | 2025  |
|             Costa Rica             |   1,839   | 2001  | 2025  |
|                Cuba                |    204    | 2002  | 2012  |
|         Dominican Republic         |   2,702   | 2000  | 2025  |
|              Ecuador               |   2,644   | 2003  | 2025  |
|            El Salvador             |   1,845   | 2010  | 2024  |
|             Guatemala              |   2,139   | 2002  | 2024  |
|               Haiti                |     0     |  nan  |  nan  |
|              Honduras              |   2,143   | 2005  | 2025  |
|              Jamaica               |    621    | 2008  | 2014  |
|               Mexico               |   1,619   | 2013  | 2024  |
|             Nicaragua              |    269    | 2001  | 2014  |
|               Panama               |    918    | 2003  | 2024  |
|              Paraguay              |     0     |  nan  |  nan  |
|                Peru                |    516    | 2022  | 2025  |
|            Puerto Rico             |     0     |  nan  |  nan  |
|        Trinidad and Tobago         |    537    | 2019  | 2024  |
|              Uruguay               |   2,701   | 2001  | 2024  |
| Venezuela (Bolivarian Republic of) |     0     |  nan  |  nan  |
+------------------------------------+-----------+-------+-------+

## Employment by sex and economic activity - ISIC level 2 (thousands) [Annual]

**Information on dataset**

With the aim of promoting international comparability, statistics presented on ILOSTAT are based on standard international definitions wherever feasible and may differ from official national figures. This series is based on the 13th ICLS definitions. For time series comparability, it includes countries that have implemented the 19th ICLS standards, for which data are also available in the Work Statistics -- 19th ICLS (WORK) database. The employed comprise all persons of working age who, during a specified brief period, were in one of the following categories: a) paid employment (whether at work or with a job but not at work); or b) self-employment (whether at work or with an enterprise but not at work). Data disaggregated by economic activity are provided according to the latest version of the International Standard Industrial Classification of All Economic Activities (ISIC) available for that year. Data may have been regrouped from national classifications, which may not be strictly compatible with ISIC. For more information, refer to the [Labour Force Statistics (LFS and STLFS) database description](https://ilostat.ilo.org/methods/concepts-and-definitions/description-labour-force-statistics/).

+ Subject: Employment
+ Database: Labour Force Statistics (LFS)
+ Id: EMP_TEMP_SEX_EC2_NB_A
+ Time period: 1989 - 2025
+ Last updated: 19/03/2026 17:54:18
+ Number of records: 417763

In [221]:
url = "https://rplumber.ilo.org/data/indicator?id=EMP_TEMP_SEX_EC2_NB_A&type=label&format=.csv"

df4 = read_csv(url)
df4.head()

,ref_area.label,source.label,indicator.label,sex.label,classif1.label,time,obs_value,obs_status.label,note_indicator.label,note_source.label
0,Afghanistan,LFS - Labour Force Survey,Employment by sex and economic activity - ISIC...,Total,"Economic activity (ISIC-Rev.4), 2 digit level:...",2021,7679.474,NaN,NaN,Repository: ILO-STATISTICS - Micro data proces...
1,Afghanistan,LFS - Labour Force Survey,Employment by sex and economic activity - ISIC...,Total,"Economic activity (ISIC-Rev.4), 2 digit level:...",2021,1185.836,NaN,NaN,Repository: ILO-STATISTICS - Micro data proces...
2,Afghanistan,LFS - Labour Force Survey,Employment by sex and economic activity - ISIC...,Total,"Economic activity (ISIC-Rev.4), 2 digit level:...",2021,NaN,Unreliable,NaN,Repository: ILO-STATISTICS - Micro data proces...
3,Afghanistan,LFS - Labour Force Survey,Employment by sex and economic activity - ISIC...,Total,"Economic activity (ISIC-Rev.4), 2 digit level:...",2021,10.782,NaN,NaN,Repository: ILO-STATISTICS - Micro data proces...
4,Afghanistan,LFS - Labour Force Survey,Employment by sex and economic activity - ISIC...,Total,"Economic activity (ISIC-Rev.4), 2 digit level:...",2021,17.613,NaN,NaN,Repository: ILO-STATISTICS - Micro data proces...

In [222]:
summarize_by_country(df4, latam_countries)

+------------------------------------+-----------+-------+-------+
|                País                | Registros | Desde | Hasta |
+------------------------------------+-----------+-------+-------+
|             Argentina              |   3,090   | 2011  | 2024  |
|  Bolivia (Plurinational State of)  |   5,399   | 1989  | 2024  |
|               Brazil               |   5,379   | 2002  | 2025  |
|               Chile                |    981    | 2011  | 2020  |
|              Colombia              |   4,731   | 2002  | 2025  |
|             Costa Rica             |   3,618   | 2001  | 2025  |
|                Cuba                |     0     |  nan  |  nan  |
|         Dominican Republic         |   5,229   | 2000  | 2025  |
|              Ecuador               |   5,415   | 2001  | 2025  |
|            El Salvador             |   3,762   | 2010  | 2024  |
|             Guatemala              |   4,096   | 2002  | 2024  |
|               Haiti                |     0     |  nan  |  nan  |
|              Honduras              |   4,123   | 2005  | 2025  |
|              Jamaica               |   1,236   | 2008  | 2014  |
|               Mexico               |     0     |  nan  |  nan  |
|             Nicaragua              |    506    | 2001  | 2014  |
|               Panama               |   2,539   | 1997  | 2024  |
|              Paraguay              |     0     |  nan  |  nan  |
|                Peru                |   6,720   | 1997  | 2025  |
|            Puerto Rico             |     0     |  nan  |  nan  |
|        Trinidad and Tobago         |     0     |  nan  |  nan  |
|              Uruguay               |   5,814   | 1998  | 2024  |
| Venezuela (Bolivarian Republic of) |   1,500   | 2005  | 2017  |
+------------------------------------+-----------+-------+-------+

## SDG indicator 8.5.1 - Average hourly earnings of employees by sex (local currency) [Annual]

**Information on dataset**

Data may differ from nationally reported figures and the Global SDG Indicators Database due to differences in sources and/or reference years. This indicator presents data by sex on employees' average hourly earnings. The concept of earnings, as applied in wage statistics, relates to gross remuneration in cash and in kind paid to employees, as a rule at regular intervals, for time worked or work done together with remuneration for time not worked, such as annual vacation, other type of paid leave or holidays. Earnings exclude employers' contributions in respect of their employees paid to social security and pension schemes and also the benefits received by employees under these schemes. Earnings also exclude severance and termination pay. Data are also disaggregated by occupation. Statistics on average hourly earnings by sex are the basis for the calculation of the gender pay gap. Data disaggregated by occupation are provided according to the latest version of the International Standard Classification of Occupations (ISCO). Data may have been regrouped from the national classifications, which may not be strictly compatible with ISCO. For more information, refer to the [Labour Market-related SDG Indicators (ILOSDG) database description](https://ilostat.ilo.org/methods/concepts-and-definitions/description-sustainable-development-labour-market-indicators/).


+ Subject: Earnings
+ Database: SDG Labour Market Indicators (ILOSDG)
+ Id: SDG_0851_SEX_OCU_NB_A
+ Time period: 2000 - 2025
+ Last updated: 19/03/2026 17:48:04
+ Number of records: 44590

In [223]:
url = "https://rplumber.ilo.org/data/indicator?id=SDG_0851_SEX_OCU_NB_A&type=label&format=.csv"

df5 = read_csv(url)
df5.head()

,ref_area.label,source.label,indicator.label,sex.label,classif1.label,time,obs_value,obs_status.label,note_classif.label,note_indicator.label,note_source.label
0,Afghanistan,LFS - Labour Force Survey,SDG indicator 8.5.1 - Average hourly earnings ...,Total,Occupation (Skill level): Total,2020,90.93,Break in series,NaN,Currency: AFG - Afghani (AFN) | Break in serie...,Repository: ILO-STATISTICS - Micro data proces...
1,Afghanistan,LFS - Labour Force Survey,SDG indicator 8.5.1 - Average hourly earnings ...,Total,Occupation (Skill level): Skill levels 3 and 4...,2020,151.98,Break in series,NaN,Currency: AFG - Afghani (AFN) | Break in serie...,Repository: ILO-STATISTICS - Micro data proces...
2,Afghanistan,LFS - Labour Force Survey,SDG indicator 8.5.1 - Average hourly earnings ...,Total,Occupation (Skill level): Skill level 2 ~ medium,2020,61.85,Break in series,NaN,Currency: AFG - Afghani (AFN) | Break in serie...,Repository: ILO-STATISTICS - Micro data proces...
3,Afghanistan,LFS - Labour Force Survey,SDG indicator 8.5.1 - Average hourly earnings ...,Total,Occupation (Skill level): Skill level 1 ~ low,2020,43.60,Break in series,NaN,Currency: AFG - Afghani (AFN) | Break in serie...,Repository: ILO-STATISTICS - Micro data proces...
4,Afghanistan,LFS - Labour Force Survey,SDG indicator 8.5.1 - Average hourly earnings ...,Total,Occupation (Skill level): Not elsewhere classi...,2020,63.98,Break in series,NaN,Currency: AFG - Afghani (AFN) | Break in serie...,Repository: ILO-STATISTICS - Micro data proces...

In [224]:
summarize_by_country(df5, latam_countries)

+------------------------------------+-----------+-------+-------+
|                País                | Registros | Desde | Hasta |
+------------------------------------+-----------+-------+-------+
|             Argentina              |    894    | 2000  | 2024  |
|  Bolivia (Plurinational State of)  |     0     |  nan  |  nan  |
|               Brazil               |    714    | 2012  | 2025  |
|               Chile                |    852    | 2000  | 2024  |
|              Colombia              |   1,062   | 2002  | 2025  |
|             Costa Rica             |    780    | 2000  | 2025  |
|                Cuba                |     0     |  nan  |  nan  |
|         Dominican Republic         |    543    | 2015  | 2025  |
|              Ecuador               |    657    | 2013  | 2025  |
|            El Salvador             |    705    | 2000  | 2024  |
|             Guatemala              |    102    | 2000  | 2024  |
|               Haiti                |     3     | 2001  | 2001  |
|              Honduras              |   1,044   | 2001  | 2025  |
|              Jamaica               |    363    | 2001  | 2014  |
|               Mexico               |     0     |  nan  |  nan  |
|             Nicaragua              |    56     | 2005  | 2012  |
|               Panama               |    714    | 2000  | 2024  |
|              Paraguay              |   1,179   | 2001  | 2025  |
|                Peru                |   1,253   | 2000  | 2025  |
|            Puerto Rico             |    96     | 2015  | 2020  |
|        Trinidad and Tobago         |     0     |  nan  |  nan  |
|              Uruguay               |    198    | 2020  | 2024  |
| Venezuela (Bolivarian Republic of) |    465    | 2000  | 2017  |
+------------------------------------+-----------+-------+-------+

## SDG indicator 5.5.2 - Proportion of women in managerial positions (%) [Annual]

**Information on dataset**

Data may differ from nationally reported figures and the Global SDG Indicators Database due to differences in sources and/or reference years. The female share of employment in managerial positions conveys the number of women in management as a percentage of employment in management. Employment in management is defined based on the International Standard Classification of Occupations. This series refers to total management (category 1 of ISCO-08 or ISCO-88). There is another series referring to senior and middle management only, thus excluding junior management (category 1 in both ISCO-08 and ISCO-88 minus category 14 in ISCO-08 and minus category 13 in ISCO-88). This indicator is calculated based on data on employment by sex and occupation. For more information, refer to the [Labour Market-related SDG Indicators (ILOSDG) database description](https://ilostat.ilo.org/methods/concepts-and-definitions/description-sustainable-development-labour-market-indicators/).

+ Subject: Employment
+ Database: SDG Labour Market Indicators (ILOSDG)
+ Id: SDG_T552_NOC_RT_A
+ Time period: 2000 - 2025
+ Last updated: 19/03/2026 17:48:04
+ Number of records: 4582

In [225]:
url = "https://rplumber.ilo.org/data/indicator?id=SDG_T552_NOC_RT_A&type=label&format=.csv"

df6 = read_csv(url)
df6.head()

,ref_area.label,source.label,indicator.label,time,obs_value,obs_status.label,note_classif.label,note_indicator.label,note_source.label
0,Aruba,LFS - Labour Force Survey,SDG indicator 5.5.2 - Proportion of women in m...,2011,42.751,NaN,NaN,NaN,NaN
1,Aruba,PC - Population and Housing Census,SDG indicator 5.5.2 - Proportion of women in m...,2010,40.961,NaN,NaN,NaN,Data reference period: September | Age coverag...
2,Aruba,LFS - Labour Force Survey,SDG indicator 5.5.2 - Proportion of women in m...,2007,40.250,NaN,NaN,NaN,Data reference period: October
3,Aruba,PC - Population and Housing Census,SDG indicator 5.5.2 - Proportion of women in m...,2000,35.867,NaN,NaN,NaN,Data reference period: October
4,Afghanistan,LFS - Labour Force Survey,SDG indicator 5.5.2 - Proportion of women in m...,2021,NaN,Unreliable,NaN,NaN,Repository: ILO-STATISTICS - Micro data proces...

In [226]:
summarize_by_country(df6, latam_countries)

+------------------------------------+-----------+-------+-------+
|                País                | Registros | Desde | Hasta |
+------------------------------------+-----------+-------+-------+
|             Argentina              |    22     | 2000  | 2024  |
|  Bolivia (Plurinational State of)  |    23     | 2000  | 2024  |
|               Brazil               |    24     | 2001  | 2025  |
|               Chile                |    21     | 2000  | 2025  |
|              Colombia              |    23     | 2002  | 2025  |
|             Costa Rica             |    25     | 2000  | 2025  |
|                Cuba                |     4     | 2002  | 2012  |
|         Dominican Republic         |    26     | 2000  | 2025  |
|              Ecuador               |    26     | 2000  | 2025  |
|            El Salvador             |    25     | 2000  | 2024  |
|             Guatemala              |    18     | 2002  | 2024  |
|               Haiti                |     1     | 2003  | 2003  |
|              Honduras              |    21     | 2005  | 2025  |
|              Jamaica               |    10     | 2008  | 2022  |
|               Mexico               |    18     | 2000  | 2024  |
|             Nicaragua              |     7     | 2001  | 2014  |
|               Panama               |    24     | 2001  | 2024  |
|              Paraguay              |    25     | 2001  | 2025  |
|                Peru                |    26     | 2000  | 2025  |
|            Puerto Rico             |    11     | 2000  | 2020  |
|        Trinidad and Tobago         |    20     | 2000  | 2024  |
|              Uruguay               |    25     | 2000  | 2024  |
| Venezuela (Bolivarian Republic of) |    10     | 2005  | 2017  |
+------------------------------------+-----------+-------+-------+

## SDG indicator 5.5.2 - Proportion of women in senior and middle management positions (%) [Annual]

**Information on dataset**

Data may differ from nationally reported figures and the Global SDG Indicators Database due to differences in sources and/or reference years. The female share of employment in managerial positions conveys the number of women in management as a percentage of employment in management. Employment in management is defined based on the International Standard Classification of Occupations. This series refers to senior and middle management only, thus excluding junior management (category 1 in both ISCO-08 and ISCO-88 minus category 14 in ISCO-08 and minus category 13 in ISCO-88). There is another series referring to total management (category 1 of ISCO-08 or ISCO-88). This indicator is calculated based on data on employment by sex and occupation. For more information, refer to the [Labour Market-related SDG Indicators (ILOSDG) database description](https://ilostat.ilo.org/methods/concepts-and-definitions/description-sustainable-development-labour-market-indicators/).

+ Subject: Employment
+ Database: SDG Labour Market Indicators (ILOSDG)
+ Id: SDG_0552_NOC_RT_A
+ Time period: 2000 - 2025
+ Last updated: 14/03/2026 23:28:27
+ Number of records: 1711

In [227]:
url = "https://rplumber.ilo.org/data/indicator?id=SDG_0552_NOC_RT_A&type=label&format=.csv"

df7 = read_csv(url)
df7.head()

,ref_area.label,source.label,indicator.label,time,obs_value,obs_status.label,note_indicator.label,note_source.label
0,Afghanistan,LFS - Labour Force Survey,SDG indicator 5.5.2 - Proportion of women in s...,2021,NaN,Unreliable,NaN,Repository: ILO-STATISTICS - Micro data proces...
1,Afghanistan,LFS - Labour Force Survey,SDG indicator 5.5.2 - Proportion of women in s...,2020,5.889,Unreliable,NaN,Repository: ILO-STATISTICS - Micro data proces...
2,Afghanistan,HIES - Households Living Conditions Survey,SDG indicator 5.5.2 - Proportion of women in s...,2017,4.255,Unreliable,NaN,Repository: ILO-STATISTICS - Micro data proces...
3,Afghanistan,HIES - Households Living Conditions Survey,SDG indicator 5.5.2 - Proportion of women in s...,2014,6.928,Unreliable,NaN,Repository: ILO-STATISTICS - Micro data proces...
4,Angola,LFS - Employment Survey,SDG indicator 5.5.2 - Proportion of women in s...,2024,21.956,NaN,NaN,Repository: ILO-STATISTICS - Micro data proces...

In [228]:
summarize_by_country(df7, latam_countries)

+------------------------------------+-----------+-------+-------+
|                País                | Registros | Desde | Hasta |
+------------------------------------+-----------+-------+-------+
|             Argentina              |    18     | 2004  | 2024  |
|  Bolivia (Plurinational State of)  |    20     | 2000  | 2024  |
|               Brazil               |    23     | 2002  | 2025  |
|               Chile                |     0     |  nan  |  nan  |
|              Colombia              |    23     | 2002  | 2025  |
|             Costa Rica             |    16     | 2001  | 2025  |
|                Cuba                |     2     | 2002  | 2012  |
|         Dominican Republic         |    26     | 2000  | 2025  |
|              Ecuador               |    23     | 2003  | 2025  |
|            El Salvador             |    15     | 2010  | 2024  |
|             Guatemala              |    18     | 2002  | 2024  |
|               Haiti                |     0     |  nan  |  nan  |
|              Honduras              |    20     | 2005  | 2025  |
|              Jamaica               |     7     | 2008  | 2014  |
|               Mexico               |    12     | 2013  | 2024  |
|             Nicaragua              |     3     | 2001  | 2014  |
|               Panama               |     8     | 2003  | 2024  |
|              Paraguay              |     0     |  nan  |  nan  |
|                Peru                |     4     | 2022  | 2025  |
|            Puerto Rico             |     0     |  nan  |  nan  |
|        Trinidad and Tobago         |     6     | 2019  | 2024  |
|              Uruguay               |    24     | 2001  | 2024  |
| Venezuela (Bolivarian Republic of) |     0     |  nan  |  nan  |
+------------------------------------+-----------+-------+-------+

## SDG indicator 8.3.1 - Proportion of informal employment in total employment by sex and economic activity (%) [Annual]

**Information on dataset**

Data may differ from nationally reported figures and the Global SDG Indicators Database due to differences in sources and/or reference years. This indicator conveys the share of informal employment in total employment. Employment comprises all persons of working age who, during a specified brief period, were either in paid employment (whether at work or with a job but not at work) or in self-employment (whether at work or with an enterprise but not at work). Informal employment comprises persons who in their main or secondary jobs were (a) own-account workers, employers and members of producers' cooperatives employed in their own informal sector enterprises; (b) own-account workers engaged in the production of goods exclusively for own final use by their household (e.g. subsistence farming); (c) contributing family workers, regardless of whether they work in formal or informal sector enterprises; or (d) employees holding informal jobs, whether employed by formal sector enterprises, informal sector enterprises, or as paid domestic workers by households. Data disaggregated by economic activity are provided according to the latest version of the International Standard Industrial Classification of All Economic Activities (ISIC) available for that year. Data may have been regrouped from national classifications, which may not be strictly compatible with ISIC. For more information, refer to the [Labour Market-related SDG Indicators (ILOSDG) database description](https://ilostat.ilo.org/methods/concepts-and-definitions/description-sustainable-development-labour-market-indicators/).

+ Subject: Informal economy
+ Database: SDG Labour Market Indicators (ILOSDG)
+ Id: SDG_0831_SEX_ECO_RT_A
+ Time period: 2000 - 2027
+ Last updated: 19/03/2026 17:48:04
+ Number of records: 54485

In [229]:
url = "https://rplumber.ilo.org/data/indicator?id=SDG_0831_SEX_ECO_RT_A&type=label&format=.csv"

df8 = read_csv(url)
df8.head()

,ref_area.label,source.label,indicator.label,sex.label,classif1.label,time,obs_value,obs_status.label,note_classif.label,note_indicator.label,note_source.label
0,Afghanistan,LFS - Labour Force Survey,SDG indicator 8.3.1 - Proportion of informal e...,Total,Economic activity (Broad sector): Total,2021,86.125,NaN,NaN,NaN,Repository: ILO-STATISTICS - Micro data proces...
1,Afghanistan,LFS - Labour Force Survey,SDG indicator 8.3.1 - Proportion of informal e...,Total,Economic activity (Broad sector): Agriculture,2021,99.150,NaN,NaN,NaN,Repository: ILO-STATISTICS - Micro data proces...
2,Afghanistan,LFS - Labour Force Survey,SDG indicator 8.3.1 - Proportion of informal e...,Total,Economic activity (Broad sector): Non-agriculture,2021,73.713,NaN,NaN,NaN,Repository: ILO-STATISTICS - Micro data proces...
3,Afghanistan,LFS - Labour Force Survey,SDG indicator 8.3.1 - Proportion of informal e...,Total,Economic activity (Broad sector): Industry,2021,86.758,NaN,NaN,NaN,Repository: ILO-STATISTICS - Micro data proces...
4,Afghanistan,LFS - Labour Force Survey,SDG indicator 8.3.1 - Proportion of informal e...,Total,Economic activity (Broad sector): Services,2021,62.916,NaN,NaN,NaN,Repository: ILO-STATISTICS - Micro data proces...

In [230]:
summarize_by_country(df8, latam_countries)

+------------------------------------+-----------+-------+-------+
|                País                | Registros | Desde | Hasta |
+------------------------------------+-----------+-------+-------+
|             Argentina              |    756    | 2004  | 2024  |
|  Bolivia (Plurinational State of)  |    780    | 2000  | 2024  |
|               Brazil               |    672    | 2009  | 2025  |
|               Chile                |    612    | 2010  | 2025  |
|              Colombia              |    745    | 2007  | 2025  |
|             Costa Rica             |    664    | 2010  | 2025  |
|                Cuba                |     0     |  nan  |  nan  |
|         Dominican Republic         |    936    | 2000  | 2025  |
|              Ecuador               |    872    | 2001  | 2025  |
|            El Salvador             |    396    | 2014  | 2024  |
|             Guatemala              |    684    | 2002  | 2024  |
|               Haiti                |    42     | 2012  | 2012  |
|              Honduras              |    498    | 2006  | 2017  |
|              Jamaica               |    335    | 2016  | 2023  |
|               Mexico               |    840    | 2002  | 2024  |
|             Nicaragua              |    42     | 2012  | 2012  |
|               Panama               |    666    | 2003  | 2024  |
|              Paraguay              |    697    | 2008  | 2025  |
|                Peru                |    978    | 2002  | 2025  |
|            Puerto Rico             |     0     |  nan  |  nan  |
|        Trinidad and Tobago         |     0     |  nan  |  nan  |
|              Uruguay               |    712    | 2006  | 2024  |
| Venezuela (Bolivarian Republic of) |    42     | 2017  | 2017  |
+------------------------------------+-----------+-------+-------+

## Unemployment by sex and education (thousands) [Annual]

**Information on dataset**

With the aim of promoting international comparability, statistics presented on ILOSTAT are based on standard international definitions wherever feasible and may differ from official national figures. This series is based on the 13th ICLS definitions. For time series comparability, it includes countries that have implemented the 19th ICLS standards, for which data are also available in the Work Statistics -- 19th ICLS (WORK) database. The unemployed comprise all persons of working age who were: a) without work during the reference period, i.e. were not in paid employment or self-employment; b) currently available for work, i.e. were available for paid employment or self-employment during the reference period; and c) seeking work, i.e. had taken specific steps in a specified recent period to seek paid employment or self-employment. Data disaggregated by level of education are provided on the highest level of education completed, classified according to the International Standard Classification of Education (ISCED). Data may have been regrouped from national classifications, which may not be strictly compatible with ISCED. For more information, refer to the [Education and Mismatch Indicators (EMI) database description](https://ilostat.ilo.org/methods/concepts-and-definitions/description-education-and-mismatch-indicators/).

+ Subject: Unemployment
+ Database: Education and Mismatch Indicators (EMI)
+ Id: UNE_TUNE_SEX_EDU_NB_A
+ Time period: 1970 - 2025
+ Last updated: 19/03/2026 17:45:18
+ Number of records: 78026

In [231]:
url = "https://rplumber.ilo.org/data/indicator?id=EAR_XFLS_NOC_RT_A&type=label&format=.csv"

df9 = read_csv(url)
df9.head()

,ref_area.label,source.label,indicator.label,time,obs_value,obs_status.label,note_indicator.label,note_source.label
0,Afghanistan,LFS - Labour Force Survey,Female share of low pay earners (%),2020,4.263,Break in series,Break in series: Methodology revised,Repository: ILO-STATISTICS - Micro data proces...
1,Afghanistan,HIES - Households Living Conditions Survey,Female share of low pay earners (%),2014,16.592,NaN,NaN,Repository: ILO-STATISTICS - Micro data proces...
2,Angola,LFS - Employment Survey,Female share of low pay earners (%),2024,36.101,NaN,NaN,Repository: ILO-STATISTICS - Micro data proces...
3,Angola,LFS - Employment Survey,Female share of low pay earners (%),2023,40.402,NaN,NaN,Repository: ILO-STATISTICS - Micro data proces...
4,Angola,LFS - Employment Survey,Female share of low pay earners (%),2022,36.091,NaN,NaN,Repository: ILO-STATISTICS - Micro data proces...

In [232]:
summarize_by_country(df11, latam_countries)

+------------------------------------+-----------+-------+-------+
|                País                | Registros | Desde | Hasta |
+------------------------------------+-----------+-------+-------+
|             Argentina              |    72     | 1996  | 2024  |
|  Bolivia (Plurinational State of)  |    27     | 1999  | 2024  |
|               Brazil               |    50     | 2002  | 2025  |
|               Chile                |    66     | 1990  | 2024  |
|              Colombia              |    76     | 1995  | 2025  |
|             Costa Rica             |    67     | 1995  | 2025  |
|                Cuba                |     0     |  nan  |  nan  |
|         Dominican Republic         |    33     | 2015  | 2025  |
|              Ecuador               |    76     | 1995  | 2025  |
|            El Salvador             |    42     | 2010  | 2024  |
|             Guatemala              |     9     | 2018  | 2024  |
|               Haiti                |     0     |  nan  |  nan  |
|              Honduras              |    73     | 1995  | 2025  |
|              Jamaica               |    21     | 2008  | 2014  |
|               Mexico               |     0     |  nan  |  nan  |
|             Nicaragua              |     6     | 2005  | 2012  |
|               Panama               |    75     | 1995  | 2024  |
|              Paraguay              |    81     | 1998  | 2025  |
|                Peru                |    89     | 1995  | 2025  |
|            Puerto Rico             |     6     | 2015  | 2020  |
|        Trinidad and Tobago         |    21     | 2010  | 2016  |
|              Uruguay               |    39     | 2000  | 2024  |
| Venezuela (Bolivarian Republic of) |    53     | 1995  | 2020  |
+------------------------------------+-----------+-------+-------+

## Female share of low pay earners (%) [Annual]

**Information on dataset**

With the aim of promoting international comparability, statistics presented on ILOSTAT are based on standard international definitions wherever feasible and may differ from official national figures. This measure of earnings dispersion refers to the percentage of low pay workers, among all low pay workers, who are female. For more information, refer to the [Gender Equality and Non-Discrimination Indicators (GEND) database description](https://ilostat.ilo.org/methods/concepts-and-definitions/description-gender-equality-and-non-discrimination-indicators/).

+ Subject: Income and pay inequality
+ Database: Gender Equality and Non-Discrimination Indicators (GEND)
+ Id: EAR_XFLS_NOC_RT_A
+ Time period: 1990 - 2025
+ Last updated: 19/03/2026 17:46:12
+ Number of records: 1052

In [233]:
url = "https://rplumber.ilo.org/data/indicator?id=UNE_TUNE_SEX_EDU_NB_A&type=label&format=.csv"

df10 = read_csv(url)
df10.head()

,ref_area.label,source.label,indicator.label,sex.label,classif1.label,time,obs_value,obs_status.label,note_classif.label,note_indicator.label,note_source.label
0,Afghanistan,LFS - Labour Force Survey,Unemployment by sex and education (thousands),Total,Education (Aggregate levels): Total,2021,462.411,NaN,NaN,NaN,Repository: ILO-STATISTICS - Micro data proces...
1,Afghanistan,LFS - Labour Force Survey,Unemployment by sex and education (thousands),Total,Education (Aggregate levels): Less than basic,2021,232.623,NaN,NaN,NaN,Repository: ILO-STATISTICS - Micro data proces...
2,Afghanistan,LFS - Labour Force Survey,Unemployment by sex and education (thousands),Total,Education (Aggregate levels): Basic,2021,81.747,NaN,NaN,NaN,Repository: ILO-STATISTICS - Micro data proces...
3,Afghanistan,LFS - Labour Force Survey,Unemployment by sex and education (thousands),Total,Education (Aggregate levels): Intermediate,2021,98.258,NaN,NaN,NaN,Repository: ILO-STATISTICS - Micro data proces...
4,Afghanistan,LFS - Labour Force Survey,Unemployment by sex and education (thousands),Total,Education (Aggregate levels): Advanced,2021,48.743,NaN,NaN,NaN,Repository: ILO-STATISTICS - Micro data proces...

In [234]:
summarize_by_country(df10, latam_countries)

+------------------------------------+-----------+-------+-------+
|                País                | Registros | Desde | Hasta |
+------------------------------------+-----------+-------+-------+
|             Argentina              |    810    | 2004  | 2024  |
|  Bolivia (Plurinational State of)  |   1,344   | 1991  | 2024  |
|               Brazil               |   1,425   | 1989  | 2025  |
|               Chile                |   1,056   | 1998  | 2025  |
|              Colombia              |    960    | 2002  | 2025  |
|             Costa Rica             |   1,158   | 2001  | 2025  |
|                Cuba                |    75     | 2002  | 2012  |
|         Dominican Republic         |   1,194   | 2000  | 2025  |
|              Ecuador               |   1,041   | 2000  | 2025  |
|            El Salvador             |    654    | 2010  | 2024  |
|             Guatemala              |    681    | 2002  | 2024  |
|               Haiti                |    66     | 2003  | 2012  |
|              Honduras              |    897    | 2005  | 2025  |
|              Jamaica               |    696    | 2008  | 2023  |
|               Mexico               |     0     |  nan  |  nan  |
|             Nicaragua              |    186    | 2001  | 2014  |
|               Panama               |    507    | 1997  | 2024  |
|              Paraguay              |    747    | 1998  | 2017  |
|                Peru                |    675    | 1997  | 2025  |
|            Puerto Rico             |    96     | 2015  | 2020  |
|        Trinidad and Tobago         |    201    | 2010  | 2024  |
|              Uruguay               |   1,068   | 1998  | 2024  |
| Venezuela (Bolivarian Republic of) |    408    | 2005  | 2017  |
+------------------------------------+-----------+-------+-------+

## Low pay rate by sex (%) [Annual]


**Information on dataset**

With the aim of promoting international comparability, statistics presented on ILOSTAT are based on standard international definitions wherever feasible and may differ from official national figures. This measure of earnings dispersion refers to the proportion of employees whose hourly earnings at all jobs were less than two-thirds of median hourly earnings. For more information, refer to the [Wages and Working Time Statistics (COND) database description](https://ilostat.ilo.org/methods/concepts-and-definitions/description-wages-and-working-time-statistics/).

+ Subject: Income and pay inequality
+ Database: Wages and Working Time Statistics (COND)
+ Id: EAR_XTLP_SEX_RT_A
+ Time period: 1990 - 2025
+ Last updated: 19/03/2026 17:44:15
+ Number of records: 4245

In [235]:
url = "https://rplumber.ilo.org/data/indicator?id=EAR_XTLP_SEX_RT_A&type=label&format=.csv"

df11 = read_csv(url)
df11.head()

,ref_area.label,source.label,indicator.label,sex.label,time,obs_value,obs_status.label,note_indicator.label,note_source.label
0,Afghanistan,LFS - Labour Force Survey,Low pay rate by sex (%),Total,2020,24.852,Break in series,Break in series: Methodology revised,Repository: ILO-STATISTICS - Micro data proces...
1,Afghanistan,LFS - Labour Force Survey,Low pay rate by sex (%),Male,2020,26.161,Break in series,Break in series: Methodology revised,Repository: ILO-STATISTICS - Micro data proces...
2,Afghanistan,LFS - Labour Force Survey,Low pay rate by sex (%),Female,2020,11.701,Break in series,Break in series: Methodology revised,Repository: ILO-STATISTICS - Micro data proces...
3,Afghanistan,HIES - Households Living Conditions Survey,Low pay rate by sex (%),Total,2014,19.370,NaN,NaN,Repository: ILO-STATISTICS - Micro data proces...
4,Afghanistan,HIES - Households Living Conditions Survey,Low pay rate by sex (%),Male,2014,17.547,NaN,NaN,Repository: ILO-STATISTICS - Micro data proces...

In [236]:
summarize_by_country(df11, latam_countries)

+------------------------------------+-----------+-------+-------+
|                País                | Registros | Desde | Hasta |
+------------------------------------+-----------+-------+-------+
|             Argentina              |    72     | 1996  | 2024  |
|  Bolivia (Plurinational State of)  |    27     | 1999  | 2024  |
|               Brazil               |    50     | 2002  | 2025  |
|               Chile                |    66     | 1990  | 2024  |
|              Colombia              |    76     | 1995  | 2025  |
|             Costa Rica             |    67     | 1995  | 2025  |
|                Cuba                |     0     |  nan  |  nan  |
|         Dominican Republic         |    33     | 2015  | 2025  |
|              Ecuador               |    76     | 1995  | 2025  |
|            El Salvador             |    42     | 2010  | 2024  |
|             Guatemala              |     9     | 2018  | 2024  |
|               Haiti                |     0     |  nan  |  nan  |
|              Honduras              |    73     | 1995  | 2025  |
|              Jamaica               |    21     | 2008  | 2014  |
|               Mexico               |     0     |  nan  |  nan  |
|             Nicaragua              |     6     | 2005  | 2012  |
|               Panama               |    75     | 1995  | 2024  |
|              Paraguay              |    81     | 1998  | 2025  |
|                Peru                |    89     | 1995  | 2025  |
|            Puerto Rico             |     6     | 2015  | 2020  |
|        Trinidad and Tobago         |    21     | 2010  | 2016  |
|              Uruguay               |    39     | 2000  | 2024  |
| Venezuela (Bolivarian Republic of) |    53     | 1995  | 2020  |
+------------------------------------+-----------+-------+-------+

## SDG indicator 1.1.1 - Working poverty rate by sex and age (percentage of employed living below US$3 PPP) (%) [Annual]


**Information on dataset**

The series is part of the ILO modelled estimates and is harmonized to account for differences in national data and scope of coverage, collection and tabulation methodologies as well as for other country-specific factors. The working poverty rate conveys the percentage of employed persons living in poverty in spite of being employed. Poverty is defined using the international poverty line of US$3 per day in purchasing power parity (PPP). For more information, refer to the [Labour Market-related SDG Indicators (ILOSDG) database description](https://ilostat.ilo.org/methods/concepts-and-definitions/description-sustainable-development-labour-market-indicators/).

+ Subject: Working poverty
+ Database: SDG Labour Market Indicators (ILOSDG)
+ Id: SDG_0111_SEX_AGE_RT_A
+ Time period: 2000 - 2025
+ Last updated: 03/12/2025 19:32:36
+ Number of records: 42030

In [237]:
url = "https://rplumber.ilo.org/data/indicator?id=SDG_0111_SEX_AGE_RT_A&type=label&format=.csv"

df12 = read_csv(url)
df12.head()

,ref_area.label,source.label,indicator.label,sex.label,classif1.label,time,obs_value,obs_status.label
0,Angola,ILO - Modelled Estimates,SDG indicator 1.1.1 - Working poverty rate by ...,Total,"Age (Youth, adults): 15+",2025,40.096,Adjusted
1,Angola,ILO - Modelled Estimates,SDG indicator 1.1.1 - Working poverty rate by ...,Total,"Age (Youth, adults): 15+",2024,40.022,Adjusted
2,Angola,ILO - Modelled Estimates,SDG indicator 1.1.1 - Working poverty rate by ...,Total,"Age (Youth, adults): 15+",2023,39.713,Adjusted
3,Angola,ILO - Modelled Estimates,SDG indicator 1.1.1 - Working poverty rate by ...,Total,"Age (Youth, adults): 15-24",2023,47.817,Adjusted
4,Angola,ILO - Modelled Estimates,SDG indicator 1.1.1 - Working poverty rate by ...,Total,"Age (Youth, adults): 25+",2023,37.553,Adjusted

In [238]:
summarize_by_country(df14, latam_countries)

+------------------------------------+-----------+-------+-------+
|                País                | Registros | Desde | Hasta |
+------------------------------------+-----------+-------+-------+
|             Argentina              |    218    | 2000  | 2025  |
|  Bolivia (Plurinational State of)  |    218    | 2000  | 2025  |
|               Brazil               |    218    | 2000  | 2025  |
|               Chile                |    218    | 2000  | 2025  |
|              Colombia              |    218    | 2000  | 2025  |
|             Costa Rica             |    218    | 2000  | 2025  |
|                Cuba                |     0     |  nan  |  nan  |
|         Dominican Republic         |    218    | 2000  | 2025  |
|              Ecuador               |    218    | 2000  | 2025  |
|            El Salvador             |    218    | 2000  | 2025  |
|             Guatemala              |    218    | 2000  | 2025  |
|               Haiti                |    218    | 2000  | 2025  |
|              Honduras              |    218    | 2000  | 2025  |
|              Jamaica               |    218    | 2000  | 2025  |
|               Mexico               |    218    | 2000  | 2025  |
|             Nicaragua              |    218    | 2000  | 2025  |
|               Panama               |    218    | 2000  | 2025  |
|              Paraguay              |    218    | 2000  | 2025  |
|                Peru                |    218    | 2000  | 2025  |
|            Puerto Rico             |     0     |  nan  |  nan  |
|        Trinidad and Tobago         |    218    | 2000  | 2025  |
|              Uruguay               |    218    | 2000  | 2025  |
| Venezuela (Bolivarian Republic of) |    218    | 2000  | 2025  |
+------------------------------------+-----------+-------+-------+

## Informal employment by sex, age and education (thousands) [Annual]

**Information on dataset**

With the aim of promoting international comparability, statistics presented on ILOSTAT are based on standard international definitions wherever feasible and may differ from official national figures. This series is based on the 13th ICLS definitions. For time series comparability, it includes countries that have implemented the 19th ICLS standards, for which data are also available in the Work Statistics -- 19th ICLS (WORK) database. This harmonized series for informal employment is derived using the same set of criteria across countries to improve comparability. The criteria used are based on employment status, institutional sector, destination of production, bookkeeping, registration, social security contribution, places of work and size. Data disaggregated by level of education are provided on the highest level of education completed, classified according to the International Standard Classification of Education (ISCED). Data may have been regrouped from national classifications, which may not be strictly compatible with ISCED.
For more information, refer to the [Education and Mismatch Indicators (EMI) database description](https://ilostat.ilo.org/methods/concepts-and-definitions/description-education-and-mismatch-indicators/).

+ Subject: Informal economy
+ Database: Education and Mismatch Indicators (EMI)
+ Id: EMP_NIFL_SEX_AGE_EDU_NB_A
+ Time period: 1997 - 2025
+ Last updated: 19/03/2026 17:45:18
+ Number of records: 597153

In [239]:
url = "https://rplumber.ilo.org/data/indicator?id=EMP_NIFL_SEX_AGE_EDU_NB_A&type=label&format=.csv"

df13 = read_csv(url)
df13.head()

/tmp/ipykernel_159/1301434483.py:11: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(StringIO(response.text))

,ref_area.label,source.label,indicator.label,sex.label,classif1.label,classif2.label,time,obs_value,obs_status.label,note_classif.label,note_indicator.label,note_source.label
0,Afghanistan,LFS - Labour Force Survey,"Informal employment by sex, age and education ...",Total,"Age (Youth, adults): 15+",Education (Aggregate levels): Total,2021,6613.952,NaN,NaN,NaN,Repository: ILO-STATISTICS - Micro data proces...
1,Afghanistan,LFS - Labour Force Survey,"Informal employment by sex, age and education ...",Total,"Age (Youth, adults): 15+",Education (Aggregate levels): Less than basic,2021,4513.029,NaN,NaN,NaN,Repository: ILO-STATISTICS - Micro data proces...
2,Afghanistan,LFS - Labour Force Survey,"Informal employment by sex, age and education ...",Total,"Age (Youth, adults): 15+",Education (Aggregate levels): Basic,2021,1131.457,NaN,NaN,NaN,Repository: ILO-STATISTICS - Micro data proces...
3,Afghanistan,LFS - Labour Force Survey,"Informal employment by sex, age and education ...",Total,"Age (Youth, adults): 15+",Education (Aggregate levels): Intermediate,2021,637.441,NaN,NaN,NaN,Repository: ILO-STATISTICS - Micro data proces...
4,Afghanistan,LFS - Labour Force Survey,"Informal employment by sex, age and education ...",Total,"Age (Youth, adults): 15+",Education (Aggregate levels): Advanced,2021,236.242,NaN,NaN,NaN,Repository: ILO-STATISTICS - Micro data proces...

In [240]:
summarize_by_country(df13, latam_countries)

+------------------------------------+-----------+-------+-------+
|                País                | Registros | Desde | Hasta |
+------------------------------------+-----------+-------+-------+
|             Argentina              |     0     |  nan  |  nan  |
|  Bolivia (Plurinational State of)  |  17,008   | 1999  | 2024  |
|               Brazil               |  11,016   | 2009  | 2025  |
|               Chile                |  13,025   | 2010  | 2025  |
|              Colombia              |  12,709   | 2007  | 2025  |
|             Costa Rica             |  11,836   | 2010  | 2025  |
|                Cuba                |     0     |  nan  |  nan  |
|         Dominican Republic         |  18,510   | 2000  | 2025  |
|              Ecuador               |  16,449   | 2001  | 2025  |
|            El Salvador             |   7,627   | 2014  | 2024  |
|             Guatemala              |  11,561   | 2002  | 2024  |
|               Haiti                |    768    | 2012  | 2012  |
|              Honduras              |   8,739   | 2006  | 2017  |
|              Jamaica               |   5,853   | 2016  | 2023  |
|               Mexico               |  14,400   | 2002  | 2024  |
|             Nicaragua              |    756    | 2012  | 2012  |
|               Panama               |   7,492   | 1997  | 2024  |
|              Paraguay              |   6,823   | 2008  | 2017  |
|                Peru                |   8,102   | 2002  | 2025  |
|            Puerto Rico             |     0     |  nan  |  nan  |
|        Trinidad and Tobago         |     0     |  nan  |  nan  |
|              Uruguay               |  11,130   | 2006  | 2024  |
| Venezuela (Bolivarian Republic of) |    720    | 2017  | 2017  |
+------------------------------------+-----------+-------+-------+

## Extraccion de los sets de datos

In [241]:
df.to_parquet("ILOSTAT_labour_force_by_sex_age_education.parquet", index=False)
df2.to_parquet("ILOSTAT_working_age_population_by_sex_education_status.parquet", index=False)
df3.to_parquet("ILOSTAT_employment_by_sex_occupation_isco2.parquet", index=False)
df4.to_parquet("ILOSTAT_employment_by_sex_economic_activity_isic2.parquet", index=False)
df5.to_parquet("ILOSTAT_sdg_851_hourly_earnings_by_sex.parquet", index=False)
df6.to_parquet("ILOSTAT_sdg_552_women_managerial_positions.parquet", index=False)
df7.to_parquet("ILOSTAT_sdg_552_women_senior_middle_management.parquet", index=False)
df8.to_parquet("ILOSTAT_sdg_831_informal_employment_by_sex_activity.parquet", index=False)
df9.to_parquet("ILOSTAT_unemployment_by_sex_education.parquet", index=False)
df10.to_parquet("ILOSTAT_female_share_low_pay_earners.parquet", index=False)
df11.to_parquet("ILOSTAT_low_pay_rate_by_sex.parquet", index=False)
df12.to_parquet("ILOSTAT_sdg_111_working_poverty_rate_by_sex_age.parquet", index=False)
df13.to_parquet("ILOSTAT_informal_employment_by_sex_age_education.parquet", index=False)

# 🌎 Comisión Económica para América Latina y el Caribe (CEPAL)

La **CEPAL** es una de las cinco comisiones regionales de las Naciones Unidas, fundada en 1948
con sede en Santiago de Chile. Su misión es contribuir al desarrollo económico y social de
América Latina y el Caribe mediante investigación, análisis y asistencia técnica a los países
de la región.

## Misión
Promover el desarrollo económico y social de América Latina y el Caribe a través de la
cooperación y la integración regional.

## CEPALSTAT
**CEPALSTAT** es el portal de estadísticas de la CEPAL, que centraliza indicadores económicos,
sociales y ambientales de los países de la región. Sus datos provienen de fuentes nacionales,
organismos internacionales (como la OIT, OMS, UNESCO) y producción propia a través de
**CELADE** (Centro Latinoamericano y Caribeño de Demografía).

## Relevancia para este análisis
CEPALSTAT ofrece mayor granularidad regional que otras fuentes globales, con indicadores
específicos para América Latina y el Caribe en las siguientes áreas:

| Área | Ejemplos |
|------|---------|
| Demografía | Población por sexo, edad y país |
| Género | Participación laboral, violencia, autonomía |
| Trabajo | Empleo, informalidad, brechas salariales |
| ODS | Seguimiento de los 17 objetivos para la región |

## Diferencia con ILO/ILOSTAT

| | ILO | CEPALSTAT |
|---|---|---|
| Cobertura | Global | América Latina y el Caribe |
| Foco | Estándares y mercado laboral | Social, económico y ambiental |
| Demografía | Limitada | CELADE (proyecciones 1950-2100) |
| Granularidad regional | Media | Alta |

## Fuente de datos
Los datos utilizados en este notebook provienen de la **API pública de CEPALSTAT**,
accesible en `https://statistics.cepal.org/portal/cepalstat/open-data.html?lang=es#/`.

> 📎 Sitio oficial: [cepal.org](https://www.cepal.org) | Datos: [estadisticas.cepal.org](https://estadisticas.cepal.org)

In [242]:
# @title
import requests
from rich import print_json
import json

def request_api(api):
    response = requests.get(api)
    response.raise_for_status()
    return response.json()

api = "https://api-cepalstat.cepal.org/cepalstat/api/v1/thematic-tree?lang=en&format=json"
data = request_api(api)

### Menu Principal de la API

In [243]:
# @title
import ipywidgets as widgets
from IPython.display import display, clear_output, JSON

selected_indicator = {'id': None, 'name': None}
out = widgets.Output()
box = widgets.HBox([])

def make_options(children):
    return [(f"[{i}] {x['name']}", i) for i, x in enumerate(children)]

def rebuild(level, indices):
    current_selects = list(box.children)[:level]

    try:
        node = data['body']
        for idx in indices:
            node = node['children'][idx]

        children = node.get('children', [])

        if not children:
            with out:
                clear_output()
                selected_indicator['id']   = node.get('indicator_id')
                selected_indicator['name'] = node.get('name')
                display(JSON(node))
        else:
            with out:
                clear_output()

        if children:
            new_sel = widgets.Select(
                options=make_options(children),
                description=f'Nivel {level}:',
                rows=8,
                layout=widgets.Layout(width='300px')
            )

            def make_observer(lvl, idxs):
                def observer(change):
                    if change['new'] is not None:
                        rebuild(lvl + 1, idxs + [change['new']])
                return observer

            new_sel.observe(make_observer(level, indices[:]), names='value')
            current_selects.append(new_sel)
            box.children = tuple(current_selects)

            rebuild(level + 1, indices + [0])
            return

        box.children = tuple(current_selects)

    except (IndexError, KeyError):
        box.children = tuple(current_selects)

# nivel 0
root_children = data['body'].get('children', [])
sel0 = widgets.Select(
    options=make_options(root_children),
    description='Nivel 0:',
    rows=8,
    layout=widgets.Layout(width='300px')
)

def on_sel0(change):
    if change['new'] is not None:
        rebuild(1, [change['new']])

sel0.observe(on_sel0, names='value')
box.children = (sel0,)

display(box, out)

# expande desde el primer item
rebuild(1, [0])

HBox(children=(Select(description='Nivel 0:', layout=Layout(width='300px'), options=(('[0] Demographic and soc…

Output()

### Set de datos

In [258]:
# @title
def build_dim_lookup(dimensions):
    """
    Retorna un dict: { 'dim_{id}': { member_id: member_name } }
    """
    lookup = {}
    for dim in dimensions:
        key = f"dim_{dim['id']}"
        lookup[key] = {m['id']: m['name'] for m in dim['members']}
    return lookup

indicator_id = selected_indicator['id']

# Indicadores
api_ind = f"https://api-cepalstat.cepal.org/cepalstat/api/v1/indicator/{indicator_id}/records?lang=en&format=json"
data_ind = request_api(api_ind)
df_ind = pd.DataFrame(data_ind['body']['data'])

#Dimensiones
api_dim = f"https://api-cepalstat.cepal.org/cepalstat/api/v1/indicator/{indicator_id}/dimensions?lang=en&format=json"
dim_data = request_api(api_dim)
dimensions = dim_data['body']['dimensions']
lookup = build_dim_lookup(dimensions)

#Mappeamos codigos
for col, mapping in lookup.items():
    if col in df_ind.columns:
        df_ind[col] = df_ind[col].map(mapping)

#Renombramos columnas
col_names = {f"dim_{dim['id']}": dim['name'].replace("__ESTANDAR", "").lower() for dim in dimensions}
df_ind.rename(columns=col_names, inplace=True)

# metadata del indicador
api_sources = f"https://api-cepalstat.cepal.org/cepalstat/api/v1/indicator/{indicator_id}/sources?lang=en&format=json"
api_notes   = f"https://api-cepalstat.cepal.org/cepalstat/api/v1/indicator/{indicator_id}/footnotes?lang=en&format=json"

sources = request_api(api_sources)
notes   = request_api(api_notes)

source_lookup = {s['id']: s['description'] for s in sources['body']['sources']}
notes_lookup = {str(n['id']): n['description'] for n in notes['body']['footnotes']}

df_ind['source_id']  = df_ind['source_id'].map(source_lookup)
df_ind['notes_ids']  = df_ind['notes_ids'].map(notes_lookup)

df_ind.rename(columns={'source_id': 'source', 'notes_ids': 'note'}, inplace=True)
df_ind.head()

,value,source,note,iso3,country,quintile,years,geographical area,sex
0,68.69999694824219,Based on household surveys from different coun...,The average for Latin America comprises the ho...,None,Latin America (weighted average),Quintile 5,2002,National,Men
1,88.69999694824219,Based on household surveys from different coun...,The average for Latin America comprises the ho...,None,Latin America (weighted average),Total quintile,2002,National,Men
2,96.0999984741211,Based on household surveys from different coun...,The average for Latin America comprises the ho...,None,Latin America (weighted average),Quintile 1,2002,National,Women
3,94.9000015258789,Based on household surveys from different coun...,The average for Latin America comprises the ho...,None,Latin America (weighted average),Quintile 2,2002,National,Women
4,93.4000015258789,Based on household surveys from different coun...,The average for Latin America comprises the ho...,None,Latin America (weighted average),Quintile 3,2002,National,Women

In [259]:
summarize_by_country(df_ind, latam_countries, country_col='country', time_col='years')

+------------------------------------+-----------+-------+-------+
|                País                | Registros | Desde | Hasta |
+------------------------------------+-----------+-------+-------+
|             Argentina              |    162    | 2016  | 2024  |
|  Bolivia (Plurinational State of)  |    972    | 2005  | 2023  |
|               Brazil               |    972    | 2001  | 2019  |
|               Chile                |    486    | 2000  | 2022  |
|              Colombia              |    756    | 2008  | 2021  |
|             Costa Rica             |   1,080   | 2000  | 2024  |
|                Cuba                |     0     |  nan  |  nan  |
|         Dominican Republic         |    648    | 2013  | 2024  |
|              Ecuador               |    540    | 2008  | 2017  |
|            El Salvador             |   1,134   | 2001  | 2023  |
|             Guatemala              |    216    | 2000  | 2023  |
|               Haiti                |     0     |  nan  |  nan  |
|              Honduras              |    864    | 2004  | 2024  |
|              Jamaica               |     0     |  nan  |  nan  |
|               Mexico               |    648    | 2002  | 2024  |
|             Nicaragua              |    162    | 2005  | 2014  |
|               Panama               |    432    | 2014  | 2022  |
|              Paraguay              |   1,296   | 2001  | 2024  |
|                Peru                |   1,296   | 2001  | 2024  |
|            Puerto Rico             |     0     |  nan  |  nan  |
|        Trinidad and Tobago         |     0     |  nan  |  nan  |
|              Uruguay               |   1,008   | 2001  | 2024  |
| Venezuela (Bolivarian Republic of) |    216    | 2003  | 2014  |
+------------------------------------+-----------+-------+-------+

#### Metadata

In [260]:
# @title
from IPython.display import Markdown
from bs4 import BeautifulSoup
import re

def clean_methodology(text):
    soup = BeautifulSoup(text, 'html.parser')

    # detecta CUALQUIER fraccion con patron border-bottom
    for container in soup.find_all('div', style=lambda s: s and 'text-align: center' in s):
        fractions = []

        for inline in container.find_all('div', style=lambda s: s and 'inline-block' in s):
            # prefijo: span antes de la fraccion (ej: "yPC = ")
            prefix = ''
            prefix_span = inline.find('span')
            if prefix_span:
                prefix = prefix_span.get_text().strip()

            # numerador: div con border-bottom
            num_div = inline.find('div', style=lambda s: s and 'border-bottom' in s)
            if not num_div:
                continue

            # denominador: siguiente sibling
            den_div = num_div.find_next_sibling('div')
            if not den_div:
                continue

            num = num_div.get_text().strip()
            den = den_div.get_text().strip()

            latex = f'{prefix}\\frac{{{num}}}{{{den}}}'
            fractions.append(latex)

        if fractions:
            container.replace_with(f'\n\n$${"  ".join(fractions)}$$\n\n')

    # listas
    for li in soup.find_all('li'):
        li.replace_with(f'\n- {li.get_text().strip()}')

    # parrafos
    for p in soup.find_all('p'):
        p.replace_with(f'\n\n{p.get_text().strip()}')

    result = soup.get_text()
    result = re.sub(r'\n{3,}', '\n\n', result)
    result = re.sub(r'[ \t]{2,}', ' ', result)
    return result.strip()

def build_indicator_markdown(m, dimensions, sources, notes):

    # dimensiones
    dim_lines = []
    for dim in dimensions:
        members = [mb['name'] for mb in dim['members'] if mb.get('in') == 1]
        dim_lines.append(f"- **{dim['name']}** ({len(members)} valores activos): {', '.join(members[:5])}{'...' if len(members) > 5 else ''}")

    # fuentes
    source_lines = [f"- {s['description']} ([{s['organization_acronym']}]({s['organization_url']}))"
                    for s in sources['body']['sources']]

    # notas
    note_lines = [f"- `{n['id']}`: {n['description'][:120]}..." for n in notes['body']['footnotes']]

    md = f"""# {m['indicator_name']}

## Overview
| Campo | Valor |
|---|---|
| **ID** | {m['indicator_id']} |
| **Tema** | {m['theme']} |
| **Área** | {m['area']} |
| **Unidad** | {m['unit']} |
| **Última actualización** | {m['last_update']} |
| **Decimales** | {m['decimals']} |

## Definición
{m['definition']}

## Cobertura
{m['data_features']}

## Dimensiones
{chr(10).join(dim_lines)}

## Metodología
{clean_methodology(m['calculation_methodology'])}

## Fuentes
{chr(10).join(source_lines)}

## Notas
{chr(10).join(note_lines)}

## Comentarios
{m['comments']}
"""
    return md

api_meta = f"https://api-cepalstat.cepal.org/cepalstat/api/v1/indicator/{indicator_id}/metadata?lang=en&format=json"

meta = request_api(api_meta)
meta = meta['body']['metadata']

md = build_indicator_markdown(meta, dimensions, sources, notes)

display(Markdown(md))

# Population without internet access at home by quintiles, sex and area

## Overview
| Campo | Valor |
|---|---|
| **ID** | 4623 |
| **Tema** | Social Indicators and Statistics |
| **Área** | Housing & Basic Services |
| **Unidad** | Percentage |
| **Última actualización** | Oct 30 2025  5:19PM |
| **Decimales** | 1 |

## Definición
This indicator shows the proportion of people who live in households that do not have internet access. The greater the number of people who do not have internet access, the lower their quality of life, connectivity and level of participation.

## Cobertura


## Dimensiones
- **Sex__ESTANDAR** (3 valores activos): Both sexes, Men, Women
- **Country__ESTANDAR** (20 valores activos): Argentina, Bolivia (Plurinational State of), Brazil, Chile, Colombia...
- **Geographical area** (3 valores activos): National, Rural, Urban
- **Quintile** (6 valores activos): Quintile 1, Quintile 2, Quintile 3, Quintile 4, Quintile 5...
- **Years__ESTANDAR** (25 valores activos): 2000, 2001, 2002, 2003, 2004...

## Metodología
Quotient between the number of people who do not have internet access at home, divided by the total number of people (denominator). The result is multiplied by 100. The information is presented disaggregated by per capita household income quintiles, geographic area and sex.

$$P =\frac{100 * nijkl}{Nijl} \frac{100 * nijkl}{Nijl}$$

Where:

- nijkl = Number of people without Internet access in household k, by per capita income quintile l, area j and sex i

- Nijl = Total number of people by quintile of per capita income l, area j and sex i

In this indicator, households with Internet access are considered to be those that have a connection to this service at home, reaching them by fiber optics, coaxial cable or by antenna.

## Fuentes
- Based on household surveys from different countries . Household Survey Data Bank (BADEHOG). ([ECLAC](https://www.cepal.org/))

## Notas
- `86`: Urban areas....
- `337`: Reference period: Fourth quarter....
- `355`: Reference period: May....
- `366`: Second semester....
- `8608`: September. Comparable series up to 2015....
- `8609`: Annual data. Comparable series since 2016...
- `8611`: Comparable series from 2008....
- `8612`: Comparable series until 2009....
- `8613`: Comparable series from 2010....
- `8615`: Reference period: June....
- `8618`: October. Comparable series until 2015....
- `8619`: Annual data. Comparable series since 2017....
- `8620`: The average for Latin America comprises the household surveys conducted by the countries in the corresponding year; when...
- `8648`: May to December 2003....
- `8649`: Annual data. Comparable series since 2004....
- `10360`: March...
- `12428`: Income measurement comparable from 2016...
- `12429`: Income measurement comparable until 2014...
- `13639`: Data may not be representative. Based on fewer than 30 survey observations....
- `16003`: Fourth quarter. Comparable series up to 2021....
- `16004`: Annual data. Comparable series since 2022...

## Comentarios
<p>This indicator can be used to detect inequality in internet access linked to income level or area of residence. It allows detecting the sources of inequality and the design of policies that promote connectivity regardless of income level, for example, generating more accessible plans for the population with a low income level, public access networks, etc. It can also be used to observe the impact that changes in policy have had in the period of analysis.</p>

#### Extraccion del set de datos

In [261]:
import re
from datetime import datetime

def clean_filename(name):
    name = name.lower().strip()
    name = re.sub(r'\s+', '_', name)
    name = re.sub(r'[^a-z0-9_]', '', name)
    return name

indicator_name = clean_filename(meta['indicator_name'])
timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')

df_ind.to_parquet(f"CEPALSTAT_{indicator_id}_{indicator_name}.parquet", index=False)

# 🌐 Unión Internacional de Telecomunicaciones (ITU) via Banco Mundial

La **ITU** (International Telecommunication Union) es el organismo especializado de las
Naciones Unidas para las tecnologías de la información y la comunicación (TIC), fundado
en 1865 con sede en Ginebra, Suiza. Es la principal fuente global de estadísticas sobre
conectividad y uso de internet desagregadas por sexo, edad y país.

## Misión
Facilitar la conectividad internacional en redes de comunicación y garantizar que las TIC
sean accesibles para todos, promoviendo el desarrollo digital inclusivo a nivel global.

## Datos utilizados

Los indicadores de uso de internet desagregados por sexo provienen de la **API pública
del Banco Mundial**, que replica y distribuye los datos oficiales de la ITU:

| Indicador | Código | Descripción |
|-----------|--------|-------------|
| Usuarios de internet (total) | `IT.NET.USER.ZS` | % de población total que usa internet |
| Usuarios de internet (mujeres) | `IT.NET.USER.FE.ZS` | % de mujeres que usan internet |
| Usuarios de internet (hombres) | `IT.NET.USER.MA.ZS` | % de hombres que usan internet |

## Relevancia para este análisis

La brecha digital de género se calcula como la diferencia entre el porcentaje de hombres
y mujeres que usan internet por país y año. Esta variable es uno de los dos pilares del
índice de riesgo del dashboard, junto con la carga de cuidados.

| Área | Detalle |
|------|---------|
| Cobertura geográfica | 23 países de América Latina y el Caribe |
| Cobertura temporal | 2010 - 2023 |
| Granularidad | Nacional, desagregado por sexo |
| ODS relacionado | ODS 5.b — Acceso a TIC para mujeres |

## Diferencia entre fuentes

| | ITU directo | Banco Mundial (`wbgapi`) |
|---|---|---|
| Acceso | Descarga manual (Excel) | API REST programática |
| Desagregación por sexo | Sí | Sí |
| Actualización | Anual | Anual |
| Integración en Python | Scraping | `wbgapi` nativo |


> 📎 ITU: [itu.int](https://www.itu.int) | Banco Mundial: [data.worldbank.org](https://data.worldbank.org/indicator)

In [248]:
!pip install wbgapi -q

In [249]:
import wbgapi as wb

latam_codes = ['ARG', 'BOL', 'BRA', 'CHL', 'COL', 'CRI', 'CUB', 'DOM',
               'ECU', 'SLV', 'GTM', 'HTI', 'HND', 'JAM', 'MEX', 'NIC',
               'PAN', 'PRY', 'PER', 'PRI', 'TTO', 'URY', 'VEN']

## Usuarios de internet totales

In [250]:
df_internet_total = wb.data.DataFrame('IT.NET.USER.ZS', economy=latam_codes, time=range(2010, 2026))
df_internet_total.to_parquet("ITU_internet_users_pct_total.parquet", index=False)
df_internet_total.head()

,YR2010,YR2011,YR2012,YR2013,YR2014,YR2015,YR2016,YR2017,YR2018,YR2019,YR2020,YR2021,YR2022,YR2023,YR2024,YR2025
economy,,,,,,,,,,,,,,,,
ARG,45.00,51.0000,55.80,59.90,64.7000,68.0431,70.9690,74.2949,77.7000,79.9470,85.5144,87.1507,88.3754,89.2290,89.6672,NaN
BOL,22.40,30.0000,35.34,36.99,34.6016,37.4868,39.6975,43.8323,44.2861,47.4748,59.9401,65.9774,67.3612,70.2368,NaN,NaN
BRA,40.65,45.6900,48.56,51.04,54.5510,58.3280,60.8725,67.4713,70.4343,73.9124,81.3427,80.6899,80.5278,84.1506,84.4635,NaN
CHL,45.00,52.2496,55.05,58.00,61.1100,76.6296,83.5586,82.3275,84.9000,85.0176,87.4593,90.2328,93.5377,94.4574,NaN,NaN
COL,36.50,40.3509,48.98,51.70,52.5681,55.9050,58.1365,62.2599,64.1264,65.0069,69.7953,73.0284,72.7964,77.3369,NaN,NaN

## Usuarios de internet mujeres

In [251]:
# Internet users - female
df_internet_female = wb.data.DataFrame('IT.NET.USER.FE.ZS', economy=latam_codes, time=range(2010, 2026))
df_internet_female.to_parquet("ITU_internet_users_pct_female.parquet", index=False)
df_internet_female.head()

,YR2010,YR2011,YR2012,YR2013,YR2014,YR2015,YR2016,YR2017,YR2018,YR2019,YR2020,YR2021,YR2022,YR2023,YR2024,YR2025
economy,,,,,,,,,,,,,,,,
ARG,NaN,NaN,NaN,NaN,NaN,NaN,70.1150,73.4920,NaN,NaN,NaN,86.5182,88.0800,89.0300,NaN,NaN
BOL,NaN,NaN,NaN,34.2187,32.1849,34.4719,NaN,NaN,41.6667,44.4308,58.0403,63.7076,NaN,NaN,NaN,NaN
BRA,40.2503,NaN,NaN,52.8162,54.1797,57.5621,61.1209,67.3369,70.0151,73.4729,84.9105,79.7915,81.1465,85.6558,NaN,NaN
CHL,NaN,NaN,NaN,NaN,NaN,74.5307,83.6583,80.7228,NaN,NaN,NaN,NaN,NaN,93.2000,NaN,NaN
COL,36.1269,40.1722,48.2664,51.1495,52.3444,55.1597,58.1742,62.4199,64.5888,65.8968,70.7503,73.9080,73.5883,NaN,NaN,NaN

## Usuarios de internet hombres

In [252]:
df_internet_male = wb.data.DataFrame('IT.NET.USER.MA.ZS', economy=latam_codes, time=range(2010, 2024))
df_internet_male.to_parquet("ITU_internet_users_pct_male.parquet", index=False)
df_internet_male.head()

,YR2010,YR2011,YR2012,YR2013,YR2014,YR2015,YR2016,YR2017,YR2018,YR2019,YR2020,YR2021,YR2022,YR2023
economy,,,,,,,,,,,,,,
ARG,NaN,NaN,NaN,NaN,NaN,NaN,71.9057,75.1706,NaN,NaN,NaN,87.8221,88.6900,89.4400
BOL,NaN,NaN,NaN,39.9463,37.1074,40.5855,NaN,NaN,47.0067,50.6648,61.9163,68.3228,NaN,NaN
BRA,41.0911,NaN,NaN,49.1403,54.9503,59.1559,60.6047,67.6165,70.8905,74.3905,77.3330,81.6433,79.8710,82.5526
CHL,NaN,NaN,NaN,NaN,NaN,78.7092,83.4513,83.9940,NaN,NaN,NaN,NaN,NaN,95.1000
COL,36.9168,40.5355,49.7268,52.2661,52.7985,56.6751,58.0976,62.0950,63.6495,64.0882,68.7900,72.0965,71.9583,NaN

## Proporción de mujeres en trabajo doméstico

In [253]:
df_domestic_female = wb.data.DataFrame('SL.FAM.WORK.FE.ZS', economy=latam_codes, time=range(2010, 2024))
df_domestic_female.to_parquet("ITU_women_domestic_work.parquet", index=False)
df_domestic_female.head()

,YR2010,YR2011,YR2012,YR2013,YR2014,YR2015,YR2016,YR2017,YR2018,YR2019,YR2020,YR2021,YR2022,YR2023
economy,,,,,,,,,,,,,,
ARG,1.260985,1.192851,0.860028,0.796499,0.957133,0.948217,0.972526,0.987611,0.790449,0.819202,0.971207,0.854117,0.609544,0.474645
BOL,33.593895,34.264976,26.414603,29.948891,32.964055,28.118896,27.644751,30.693885,31.999260,28.305219,28.770808,27.711250,23.782873,24.186879
BRA,5.391212,4.690342,4.557191,4.546960,4.219851,4.128554,3.447136,3.543236,3.369263,3.206396,3.158110,3.164785,2.639684,2.201256
CHL,1.642613,1.521887,1.462351,1.554840,1.532308,1.435063,1.382154,1.315605,1.364424,1.100979,1.156545,1.104113,0.910720,0.900541
COL,5.665571,5.601608,5.931618,5.336649,4.976234,4.733104,4.103495,4.224417,3.918024,3.589959,3.363993,3.423945,3.163803,3.226819

## Proporción de hombres en trabajo doméstico

In [254]:
df_domestic_male = wb.data.DataFrame('SL.FAM.WORK.MA.ZS', economy=latam_codes, time=range(2010, 2024))
df_domestic_male.to_parquet("ITU_men_domestic_work.parquet", index=False)
df_domestic_male.head()

,YR2010,YR2011,YR2012,YR2013,YR2014,YR2015,YR2016,YR2017,YR2018,YR2019,YR2020,YR2021,YR2022,YR2023
economy,,,,,,,,,,,,,,
ARG,0.467154,0.404602,0.343144,0.367711,0.326228,0.314899,0.314612,0.310820,0.373772,0.374901,0.312002,0.312988,0.355409,0.224900
BOL,11.935007,11.916774,10.830134,10.436820,11.799953,9.611529,9.450073,10.299170,11.076585,11.261839,11.262990,11.137148,10.556718,10.572059
BRA,2.255504,1.868616,1.811317,1.736201,1.588651,1.600347,1.335196,1.391324,1.427732,1.373276,1.428443,1.322325,1.077808,0.910547
CHL,1.131797,1.037352,0.968957,1.009499,1.029195,0.903250,0.942822,0.853515,0.925266,0.814742,0.680127,0.622108,0.518278,0.469027
COL,2.565374,2.432197,2.432814,2.264252,2.135187,1.967790,1.712309,1.581630,1.447606,1.432987,1.473772,1.311605,1.218024,1.232024

## Proporción de tiempo dedicado a trabajo doméstico y de cuidados no remunerado, mujeres

In [255]:
df_domestic_time_female = wb.data.DataFrame('SG.TIM.UWRK.FE', economy=latam_codes, time=range(2010, 2024))
df_domestic_time_female.to_parquet("ITU_women_domestic_time_work.parquet", index=False)
df_domestic_time_female.head()

,YR2010,YR2011,YR2012,YR2013,YR2014,YR2015,YR2016,YR2017,YR2018,YR2019,YR2020,YR2021,YR2022,YR2023
economy,,,,,,,,,,,,,,
ARG,17.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
BOL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
BRA,NaN,NaN,13.18363,NaN,NaN,NaN,NaN,11.60814,NaN,NaN,NaN,NaN,NaN,NaN
CHL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
COL,NaN,NaN,NaN,17.54167,NaN,NaN,NaN,16.87229,NaN,NaN,NaN,17.64085,NaN,NaN

## Proporción de tiempo dedicado a trabajo doméstico y de cuidados no remunerado, hombres

In [256]:
df_domestic_time_male = wb.data.DataFrame('SG.TIM.UWRK.MA', economy=latam_codes, time=range(2010, 2024))
df_domestic_time_male.to_parquet("ITU_men_domestic_time_work.parquet", index=False)
df_domestic_time_male.head()

,YR2010,YR2011,YR2012,YR2013,YR2014,YR2015,YR2016,YR2017,YR2018,YR2019,YR2020,YR2021,YR2022,YR2023
economy,,,,,,,,,,,,,,
ARG,6.59722,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
BOL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
BRA,NaN,NaN,3.03476,NaN,NaN,NaN,NaN,5.13276,NaN,NaN,NaN,NaN,NaN,NaN
CHL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
COL,NaN,NaN,NaN,4.54167,NaN,NaN,NaN,4.59313,NaN,NaN,NaN,5.23624,NaN,NaN

# Fuentes pendientes de Investigar

Cada país de LATAM tiene su encuesta de hogares o de empleo en:
| País | Fuente | URL |
|------|--------|-----|
| Argentina | INDEC - EPH | https://www.indec.gob.ar/indec/web/Institucional-Indec-BasesDeDatos |
| Bolivia | INE - ECE | https://www.ine.gob.bo/index.php/encuestas-y-operativos/empleo |
| Brasil | IBGE - PNAD | https://www.ibge.gov.br/estatisticas/sociais/trabalho/9173-pesquisa-nacional-por-amostra-de-domicilios-continua-trimestral.html |
| Chile | INE - ENE | https://www.ine.gob.cl/estadisticas/sociales/mercado-laboral/ocupacion-y-desocupacion |
| Colombia | DANE - GEIH | https://microdatos.dane.gov.co/index.php/catalog/MERCADO-LABORAL |
| Costa Rica | INEC - ENAHO | https://www.inec.cr/encuestas/encuesta-nacional-de-hogares |
| Cuba | ONEI | https://www.onei.gob.cu/node/16307 |
| República Dominicana | BCRD - ENFT | https://www.bancentral.gov.do/a/d/2532-encuesta-nacional-de-fuerza-de-trabajo |
| Ecuador | INEC - ENEMDU | https://www.ecuadorencifras.gob.ec/empleo-encuesta-nacional-de-empleo-desempleo-y-subempleo |
| El Salvador | DIGESTYC - EHPM | https://www.digestyc.gob.sv/index.php/temas/des/ehpm/publicaciones-ehpm.html |
| Guatemala | INE - ENEI | https://www.ine.gob.gt/estadisticasine/index.php/encuestas/empleo-e-ingresos |
| Haití | IHSI | https://www.ihsi.ht/produit-enquete-emploi.html |
| Honduras | INE - EPHPM | https://www.ine.gob.hn/V3/ephpm |
| Jamaica | STATIN - LFS | https://statinja.gov.jm/LabourSocialInfo/LabourForce.aspx |
| México | INEGI - ENOE | https://www.inegi.org.mx/programas/enoe/15ymas |
| Nicaragua | INIDE - ECH | https://www.inide.gob.ni/Home/Encuestas |
| Panamá | INEC - EML | https://www.inec.gob.pa/publicaciones/Default3.aspx?ID_CATEGORIA=4 |
| Paraguay | DGEEC - EPH | https://www.dgeec.gov.py/microdatos/ficha.php?codigo=EPH |
| Perú | INEI - ENAHO | https://iinei.inei.gob.pe/microdatos |
| Puerto Rico | US Census - ACS | https://www.census.gov/programs-surveys/acs/data.html |
| Trinidad y Tobago | CSO - CLFS | https://cso.gov.tt/subjects/labour-and-employment |
| Uruguay | INE - ECH | https://www.ine.gub.uy/encuesta-continua-de-hogares |
| Venezuela | INE - EHM | https://www.ine.gov.ve/index.php/estadisticas-sociales/encuesta-de-hogares-por-muestreo |

## Fuentes oficiales con datos de brecha digital por género

### Globales

| Fuente | Indicadores | Acceso |
|--------|-------------|--------|
| OCDE | Digital gender gap para países miembro | https://stats.oecd.org |
| UNESCO | Acceso a TIC en educación por sexo | https://uis.unesco.org |
| OPS/OMS | Acceso a salud digital por sexo | https://www.paho.org/es |
| GSMA | Brecha de género en uso de móviles | https://www.gsma.com/connected-women |
| Web Foundation | Women's Rights Online | https://webfoundation.org |
| Alliance for Affordable Internet | Asequibilidad internet por género | https://a4ai.org |

### Regionales LATAM

| Fuente | Indicadores | Acceso |
|--------|-------------|--------|
| BID | Brecha digital de género en LATAM | https://data.iadb.org |
| OREALC/UNESCO | TIC en educación por sexo para LATAM | https://www.unesco.org/regional/latin-america |

# Push directo de los datasets a GitHub

In [257]:
from google.colab import userdata
import os

# Obtener token desde Colab Secrets
GITHUB_TOKEN = userdata.get('GITHUB_TOKEN')
GITHUB_USER = userdata.get('GITHUB_USER')
REPO_NAME = "Trabajo_Remunerado-DATA4CCION"

# Pasar variables a entorno del shell
os.environ['GITHUB_TOKEN'] = GITHUB_TOKEN
os.environ['GITHUB_USER'] = GITHUB_USER
os.environ['REPO_NAME'] = REPO_NAME

# Configurar git
!git config --global user.email "$GITHUB_USER@users.noreply.github.com"
!git config --global user.name "$GITHUB_USER"

# Clonar repo
!git clone https://$GITHUB_TOKEN@github.com/$GITHUB_USER/$REPO_NAME.git

# Copiar PARQUETs
!mkdir -p $REPO_NAME/data
!cp *.parquet $REPO_NAME/data/

# Push
%cd $REPO_NAME
!git add data/*.parquet
!git commit -m "Add raw data PARQUETs"
!git push https://$GITHUB_TOKEN@github.com/$GITHUB_USER/$REPO_NAME.git
%cd /content
!rm -rf $REPO_NAME

Cloning into 'Trabajo_Remunerado-DATA4CCION'...
remote: Enumerating objects: 51, done.
remote: Counting objects: 100% (51/51), done.
remote: Compressing objects: 100% (48/48), done.
remote: Total 51 (delta 14), reused 21 (delta 2), pack-reused 0 (from 0)
Receiving objects: 100% (51/51), 11.81 MiB | 18.92 MiB/s, done.
Resolving deltas: 100% (14/14), done.
/content/Trabajo_Remunerado-DATA4CCION
[main c371cf1] Add raw data PARQUETs
 9 files changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 data/CEPALSTAT_4623_population_without_internet_access_at_home_by_quintiles_sex_and_area.parquet
 create mode 100644 data/ITU_internet_users_pct_female.parquet
 create mode 100644 data/ITU_internet_users_pct_male.parquet
 create mode 100644 data/ITU_internet_users_pct_total.parquet
 create mode 100644 data/ITU_men_domestic_time_work.parquet
 create mode 100644 data/ITU_men_domestic_work.parquet
 create mode 100644 data/ITU_women_domestic_time_work.parquet
 create mode 100644 data/ITU_women_domestic_work.parquet
 create mode 100644 data/internet_users_pct_total.parquet
Enumerating objects: 14, done.
Counting objects: 100% (14/14), done.
Delta compression using up to 2 threads
Compressing objects: 100% (12/12), done.
Writing objects: 100% (12/12), 46.21 KiB | 9.24 MiB/s, done.
Total 12 (delta 8), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (8/8), completed with 1 local object.
To https://github.com/aletbm/Trabajo_Remunerado-DATA4CCION.git
   47173fc..c371cf1  main -> main
/content