## Fuentes de Datos

La arquitectura de datos de este estudio se fundamenta en la integración y armonización de tres repositorios internacionales clave:

\- Brecha digital: "Percentage of individuals using the Internet \- at least once a day" \| Worldbank\.
Link: https://data360\.worldbank\.org/en/indicator/ITU\_DH\_INT\_USR\_DAY?sex=F&age=Y\_GE75%2CY15T24%2CY0T14%2CY25T74&urbanisation=\_T&recentYear=false&view=datatable

\- Carga de cuidados: "Tiempo total de trabajo" \| Observatorio de Igualdad de Género de América Latina y el Caribe \(CEPAL\)\.
Link: https://oig\.cepal\.org/es/indicadores?id=2286 

 \- Edad: "Estructura de la población por sexo y por grupos de edad \(Porcentaje\)" \| CEPALSTAT\.
Link: https://statistics\.cepal\.org/portal/cepalstat/dashboard\.html?theme=1&lang=es

## Dónde se concentran las barreras al trabajo remunerado femenino: brecha digital y carga de cuidados en América Latina para identificar contextos prioritarios de intervención

Este proyecto investiga la intersección entre la brecha digital y la carga de cuidados como barreras estructurales fundamentales para el acceso de las mujeres al mercado laboral remunerado en la región de América Latina\.

1\. Alcance geográfico y temporal
La selección de la muestra comprende nueve países de América Latina, priorizados bajo el criterio de densidad y consistencia de datos en los tres repositorios integrados en este proyecto::
\- Cono Sur: Argentina, Uruguay, Chile\.
\- Región Andina: Colombia, Perú\.
\- Centroamérica y Caribe: Costa Rica, Guatemala, El Salvador, República Dominicana\.

El análisis se encuadra en el período 2021\-2025\. Se estableció esta ventana temporal breve para garantizar la actualidad de los hallazgos y permitir la generalización de conclusiones entre los años incluidos, asumiendo que las variaciones estructurales en este intervalo son mínimas y permiten una comparación válida\.

2\. Definición de Variables
La arquitectura del análisis se organiza bajo la siguiente jerarquía:
\- Variables Primarias \(Barreras\): Carga de cuidados y Brecha digital\.
\- Variable Secundaria \(Filtro\): Edad\.

3\. Propuesta de Solución basada en datos
La propuesta consiste en un mapa interactivo diseñado para un análisis dinámico y detallado\. Esta herramienta permite identificar geográficamente los nudos críticos donde las variables de brecha digital y carga de cuidados se intensifican, facilitando la detección de contextos prioritarios de intervención\.

4\. Fases del Proyecto
1\. ETL: Extracción, transformación y carga de los datos provenientes de los tres repositorios\.
2\. Análisis Exploratorio de Datos \(EDA\): Diagnóstico de patrones y concentraciones de barreras\.
3\. Construcción del Mapa Interactivo: Implementación de la capa de visualización geoespacial\.

# 1\. ETL \| Extracción, transformación y carga de datos

En esta etapa, se realiza una exploración de los tres datasets para evaluar la calidad de los mismos, tipos de datos, columnas existentes, valores faltantes y posibles duplicados\. A partir de esto, se aplicará un proceso de limpieza y transformación con el fin de unificar toda la información en un único dataset para las etapas posteriores de análisis exploratorio de datos \(EDA\) y georreferenciación en el mapa interactivo\.

## 1\.1\. Dataset 1: "Percentage of individuals using the Internet \- at least once a day"

## 1\.1\.1 Extracción y exploración del dataset

In [1]:
import pandas as pd

# Cargar el dataset
internet = pd.read_csv('/work/Uso del Internet.csv')

# Mostrar todas las columnas
internet_columns = internet.columns.tolist()
internet_columns

['STRUCTURE',
 'STRUCTURE_ID',
 'ACTION',
 'FREQ',
 'FREQ_LABEL',
 'REF_AREA',
 'REF_AREA_LABEL',
 'INDICATOR',
 'INDICATOR_LABEL',
 'SEX',
 'SEX_LABEL',
 'AGE',
 'AGE_LABEL',
 'URBANISATION',
 'URBANISATION_LABEL',
 'UNIT_MEASURE',
 'UNIT_MEASURE_LABEL',
 'COMP_BREAKDOWN_1',
 'COMP_BREAKDOWN_1_LABEL',
 'COMP_BREAKDOWN_2',
 'COMP_BREAKDOWN_2_LABEL',
 'COMP_BREAKDOWN_3',
 'COMP_BREAKDOWN_3_LABEL',
 'TIME_PERIOD',
 'OBS_VALUE',
 'AGG_METHOD',
 'AGG_METHOD_LABEL',
 'DATABASE_ID',
 'DATABASE_ID_LABEL',
 'UNIT_MULT',
 'UNIT_MULT_LABEL',
 'UNIT_TYPE',
 'UNIT_TYPE_LABEL',
 'TIME_FORMAT',
 'TIME_FORMAT_LABEL',
 'OBS_STATUS',
 'OBS_STATUS_LABEL',
 'OBS_CONF',
 'OBS_CONF_LABEL']

In [2]:
# Número total de filas y columnas del dataset
internet.shape

(13373, 39)

In [3]:
# Comprobación de los tipos de datos
internet.dtypes

STRUCTURE                  object
STRUCTURE_ID               object
ACTION                     object
FREQ                       object
FREQ_LABEL                 object
REF_AREA                   object
REF_AREA_LABEL             object
INDICATOR                  object
INDICATOR_LABEL            object
SEX                        object
SEX_LABEL                  object
AGE                        object
AGE_LABEL                  object
URBANISATION               object
URBANISATION_LABEL         object
UNIT_MEASURE               object
UNIT_MEASURE_LABEL         object
COMP_BREAKDOWN_1           object
COMP_BREAKDOWN_1_LABEL     object
COMP_BREAKDOWN_2           object
COMP_BREAKDOWN_2_LABEL     object
COMP_BREAKDOWN_3           object
COMP_BREAKDOWN_3_LABEL     object
TIME_PERIOD               float64
OBS_VALUE                 float64
AGG_METHOD                 object
AGG_METHOD_LABEL           object
DATABASE_ID                object
DATABASE_ID_LABEL          object
UNIT_MULT                 float64
UNIT_MULT_LABEL            object
UNIT_TYPE                  object
UNIT_TYPE_LABEL            object
TIME_FORMAT               float64
TIME_FORMAT_LABEL          object
OBS_STATUS                 object
OBS_STATUS_LABEL           object
OBS_CONF                   object
OBS_CONF_LABEL             object
dtype: object

In [4]:
# Verificación de valores nulos por columna
internet.isnull().sum()

STRUCTURE                   0
STRUCTURE_ID              691
ACTION                    691
FREQ                      691
FREQ_LABEL                691
REF_AREA                  691
REF_AREA_LABEL            691
INDICATOR                 691
INDICATOR_LABEL           691
SEX                       691
SEX_LABEL                 691
AGE                       691
AGE_LABEL                 691
URBANISATION              691
URBANISATION_LABEL        691
UNIT_MEASURE              691
UNIT_MEASURE_LABEL        691
COMP_BREAKDOWN_1          691
COMP_BREAKDOWN_1_LABEL    691
COMP_BREAKDOWN_2          691
COMP_BREAKDOWN_2_LABEL    691
COMP_BREAKDOWN_3          691
COMP_BREAKDOWN_3_LABEL    691
TIME_PERIOD               691
OBS_VALUE                 691
AGG_METHOD                691
AGG_METHOD_LABEL          691
DATABASE_ID               691
DATABASE_ID_LABEL         691
UNIT_MULT                 691
UNIT_MULT_LABEL           691
UNIT_TYPE                 691
UNIT_TYPE_LABEL           691
TIME_FORMAT               691
TIME_FORMAT_LABEL         691
OBS_STATUS                691
OBS_STATUS_LABEL          691
OBS_CONF                  691
OBS_CONF_LABEL            691
dtype: int64

## 1\.1\.2\. Transformación

In [5]:
df = internet.copy()

# Limpiar columnas
for c in ['SEX_LABEL', 'AGE_LABEL', 'REF_AREA_LABEL', 'INDICATOR_LABEL']:
    if c in df.columns:
        df[c] = df[c].astype(str).str.strip()

# Convertir año
df['TIME_PERIOD'] = pd.to_numeric(df['TIME_PERIOD'], errors='coerce').astype('Int64')

# Eliminar nulos clave
df = df.dropna(subset=['SEX_LABEL', 'REF_AREA_LABEL', 'TIME_PERIOD'])

# Países correctos
paises_objetivo = [
    'Argentina', 'Colombia', 'Dominican Republic', 'Costa Rica',
    'Guatemala', 'Uruguay', 'Chile', 'El Salvador', 'Peru'
]

# Filtros
mask_mujeres = df['SEX_LABEL'] == 'Female'
mask_anios = df['TIME_PERIOD'].between(2020, 2025)
mask_paises = df['REF_AREA_LABEL'].isin(paises_objetivo)
# Aplicar filtros principales
filtrado = df[mask_mujeres & mask_anios & mask_paises]

# QUEDARSE SOLO con el total (sin desglose por edad)
filtrado = filtrado[
    filtrado['AGE_LABEL'] == 'All age ranges or no breakdown by age'
]

# Seleccionar columnas incluyendo OBS_VALUE
columnas = ['REF_AREA_LABEL', 'TIME_PERIOD', 'AGE_LABEL', 'OBS_VALUE']
columnas = [col for col in columnas if col in filtrado.columns]

resultado = filtrado[columnas].sort_values(
    ['REF_AREA_LABEL', 'TIME_PERIOD']
)

print("Filas filtradas:", len(resultado))
display(resultado)

Filas filtradas: 25

,REF_AREA_LABEL,TIME_PERIOD,AGE_LABEL,OBS_VALUE
9139,Argentina,2021,All age ranges or no breakdown by age,86.5182
9140,Argentina,2022,All age ranges or no breakdown by age,88.0800
9141,Argentina,2023,All age ranges or no breakdown by age,89.0300
9142,Argentina,2024,All age ranges or no breakdown by age,89.1403
9327,Chile,2023,All age ranges or no breakdown by age,94.4025
9343,Colombia,2020,All age ranges or no breakdown by age,70.7503
9344,Colombia,2021,All age ranges or no breakdown by age,73.9080
9345,Colombia,2022,All age ranges or no breakdown by age,73.5883
9346,Colombia,2023,All age ranges or no breakdown by age,78.2038
9367,Costa Rica,2020,All age ranges or no breakdown by age,80.9004
9368,Costa Rica,2021,All age ranges or no breakdown by age,82.9258
9369,Costa Rica,2022,All age ranges or no breakdown by age,82.9603
9370,Costa Rica,2023,All age ranges or no breakdown by age,85.8248
9443,Dominican Republic,2021,All age ranges or no breakdown by age,85.8945
9444,Dominican Republic,2022,All age ranges or no breakdown by age,83.1923
9445,Dominican Republic,2024,All age ranges or no breakdown by age,91.2981
10192,El Salvador,2020,All age ranges or no breakdown by age,52.3743
9596,Guatemala,2021,All age ranges or no breakdown by age,48.5503
10097,Peru,2020,All age ranges or no breakdown by age,62.5367
10098,Peru,2021,All age ranges or no breakdown by age,69.0545
10099,Peru,2022,All age ranges or no breakdown by age,72.5428
10100,Peru,2023,All age ranges or no breakdown by age,77.3836
10101,Peru,2024,All age ranges or no breakdown by age,80.2250
10334,Uruguay,2022,All age ranges or no breakdown by age,90.8528
10335,Uruguay,2024,All age ranges or no breakdown by age,92.4471

In [6]:
print(sorted(resultado['REF_AREA_LABEL'].unique()))

['Argentina', 'Chile', 'Colombia', 'Costa Rica', 'Dominican Republic', 'El Salvador', 'Guatemala', 'Peru', 'Uruguay']

In [7]:
# Obtener el último año por país (tabla pequeña)
ultimos_anios = resultado.groupby('REF_AREA_LABEL', as_index=False)['TIME_PERIOD'].max()

# Unir con los datos originales
resultado_final = resultado.merge(
    ultimos_anios,
    on=['REF_AREA_LABEL', 'TIME_PERIOD'],
    how='inner'
)

# Ordenar
resultado_final = resultado_final.sort_values(
    ['REF_AREA_LABEL', 'AGE_LABEL']
)

display(resultado_final)

,REF_AREA_LABEL,TIME_PERIOD,AGE_LABEL,OBS_VALUE
0,Argentina,2024,All age ranges or no breakdown by age,89.1403
1,Chile,2023,All age ranges or no breakdown by age,94.4025
2,Colombia,2023,All age ranges or no breakdown by age,78.2038
3,Costa Rica,2023,All age ranges or no breakdown by age,85.8248
4,Dominican Republic,2024,All age ranges or no breakdown by age,91.2981
5,El Salvador,2020,All age ranges or no breakdown by age,52.3743
6,Guatemala,2021,All age ranges or no breakdown by age,48.5503
7,Peru,2024,All age ranges or no breakdown by age,80.2250
8,Uruguay,2024,All age ranges or no breakdown by age,92.4471

In [8]:
# Normalización de nombres de columnas para mejorar la legibilidad
resultado_final = resultado_final.rename(
    columns=
    {'REF_AREA_LABEL': 'pais',
    'TIME_PERIOD': 'anio',
    'AGE_LABEL': 'edad',
    'OBS_VALUE': 'porcentaje_uso_internet'}
)

# Mostrar el resultado
resultado_final.head(10)

,pais,anio,edad,porcentaje_uso_internet
0,Argentina,2024,All age ranges or no breakdown by age,89.1403
1,Chile,2023,All age ranges or no breakdown by age,94.4025
2,Colombia,2023,All age ranges or no breakdown by age,78.2038
3,Costa Rica,2023,All age ranges or no breakdown by age,85.8248
4,Dominican Republic,2024,All age ranges or no breakdown by age,91.2981
5,El Salvador,2020,All age ranges or no breakdown by age,52.3743
6,Guatemala,2021,All age ranges or no breakdown by age,48.5503
7,Peru,2024,All age ranges or no breakdown by age,80.2250
8,Uruguay,2024,All age ranges or no breakdown by age,92.4471

In [9]:
# Definimos diccionario de reemplazos al español
dicc_paises= {
    'Argentina': 'Argentina',
    'Chile': 'Chile',
    'Colombia': 'Colombia',
    'Costa Rica': 'Costa Rica',
    'Dominican Republic': 'Republica Dominicana', 
    'El Salvador': 'El Salvador',
    'Guatemala': 'Guatemala',
    'Peru': 'Peru',
    'Uruguay': 'Uruguay'
    }

# Aplicamos el reemplazo en la columna 'pais'
resultado_final['pais'] = resultado_final['pais'].replace(dicc_paises)

# Verificación de resultados
print("Países procesados:")
print(resultado_final['pais'].unique())

resultado_final.head(10)

Países procesados:
['Argentina' 'Chile' 'Colombia' 'Costa Rica' 'Republica Dominicana'
 'El Salvador' 'Guatemala' 'Peru' 'Uruguay']

,pais,anio,edad,porcentaje_uso_internet
0,Argentina,2024,All age ranges or no breakdown by age,89.1403
1,Chile,2023,All age ranges or no breakdown by age,94.4025
2,Colombia,2023,All age ranges or no breakdown by age,78.2038
3,Costa Rica,2023,All age ranges or no breakdown by age,85.8248
4,Republica Dominicana,2024,All age ranges or no breakdown by age,91.2981
5,El Salvador,2020,All age ranges or no breakdown by age,52.3743
6,Guatemala,2021,All age ranges or no breakdown by age,48.5503
7,Peru,2024,All age ranges or no breakdown by age,80.2250
8,Uruguay,2024,All age ranges or no breakdown by age,92.4471

In [10]:
# Estandarización de la columna 'pais' para garantizar consistencia en la clave de unión.
# Se eliminan espacios, se unifica el formato en mayúsculas y se remueven acentos.
resultado_final['pais'] = (
    resultado_final['pais']
    .str.strip()
    .str.upper()
    .str.normalize('NFKD')
    .str.encode('ascii', errors='ignore')
    .str.decode('utf-8')
)

# Mostrar resultados
resultado_final['pais'].unique()

array(['ARGENTINA', 'CHILE', 'COLOMBIA', 'COSTA RICA',
       'REPUBLICA DOMINICANA', 'EL SALVADOR', 'GUATEMALA', 'PERU',
       'URUGUAY'], dtype=object)

In [11]:
# Revisión de tipos de datos de dataframe final
resultado_final.dtypes

pais                        object
anio                         Int64
edad                        object
porcentaje_uso_internet    float64
dtype: object

In [12]:
# Inspección del dataset intermedio
resultado_final.head(10)

,pais,anio,edad,porcentaje_uso_internet
0,ARGENTINA,2024,All age ranges or no breakdown by age,89.1403
1,CHILE,2023,All age ranges or no breakdown by age,94.4025
2,COLOMBIA,2023,All age ranges or no breakdown by age,78.2038
3,COSTA RICA,2023,All age ranges or no breakdown by age,85.8248
4,REPUBLICA DOMINICANA,2024,All age ranges or no breakdown by age,91.2981
5,EL SALVADOR,2020,All age ranges or no breakdown by age,52.3743
6,GUATEMALA,2021,All age ranges or no breakdown by age,48.5503
7,PERU,2024,All age ranges or no breakdown by age,80.2250
8,URUGUAY,2024,All age ranges or no breakdown by age,92.4471

## 1\.2\. Dataset 2: "Tiempo total de trabajo"

## 1\.2\.1 Extracción y exploración del dataset

In [13]:
# Cargar el dataset
tiempo_trabajo = pd.read_csv('/work/Tiempo total de trabajo.csv', encoding='latin-1')

# Mostrar todas las columnas
columnas = tiempo_trabajo.columns.tolist()
print(columnas)

['indicator', 'Años__ESTANDAR', 'País__ESTANDAR', 'Tipos de trabajo', 'Sexo__población', 'value', 'unit', 'notes_ids', 'source_id']

In [14]:
# Número total de filas y columnas del dataset
tiempo_trabajo.shape

(27, 9)

In [15]:
# Comprobación de los tipos de datos
tiempo_trabajo.dtypes

indicator           object
Años__ESTANDAR       int64
País__ESTANDAR      object
Tipos de trabajo    object
Sexo__población     object
value               object
unit                object
notes_ids           object
source_id            int64
dtype: object

## 1\.2\.2 Transformación

In [16]:
# Se crea una copia sobre la cual realizar las transformaciones
tiempo_trabajo_copia = tiempo_trabajo.copy()

In [17]:
# Eliminación de columnas no significativas para el análisis
tiempo_trabajo_copia = tiempo_trabajo_copia.drop(
    columns=['Sexo__población', 'unit', 'notes_ids', 'source_id'],
    errors ='ignore'
)

# Mostrar el resultado
tiempo_trabajo_copia.head(5)

,indicator,Años__ESTANDAR,País__ESTANDAR,Tipos de trabajo,value
0,Tiempo total de trabajo según tipo de trabajo ...,2021,Argentina,Tiempo total de trabajo,"52,5"
1,Tiempo total de trabajo según tipo de trabajo ...,2021,Argentina,Tiempo trabajo remunerado,"19,3"
2,Tiempo total de trabajo según tipo de trabajo ...,2021,Argentina,Tiempo trabajo no remunerado,"33,2"
3,Tiempo total de trabajo según tipo de trabajo ...,2021,Colombia,Tiempo total de trabajo,"51,0"
4,Tiempo total de trabajo según tipo de trabajo ...,2021,Colombia,Tiempo trabajo remunerado,"16,9"

In [18]:
# Verificación de valores nulos por columna
tiempo_trabajo.isnull().sum()

indicator           0
Años__ESTANDAR      0
País__ESTANDAR      0
Tipos de trabajo    0
Sexo__población     0
value               0
unit                0
notes_ids           6
source_id           0
dtype: int64

In [19]:
# Normalización de nombres de columnas para mejorar la legibilidad
tiempo_trabajo_copia = tiempo_trabajo_copia.rename(
    columns=
    {'indicator': 'indicador',
    'Años__ESTANDAR': 'anios',
    'País__ESTANDAR': 'pais',
    'Tipos de trabajo': 'tipo_trabajo',
    'value': 'promedio_horas_semanales'
    }
)

# Mostrar el resultado
tiempo_trabajo_copia.head(5)

,indicador,anios,pais,tipo_trabajo,promedio_horas_semanales
0,Tiempo total de trabajo según tipo de trabajo ...,2021,Argentina,Tiempo total de trabajo,"52,5"
1,Tiempo total de trabajo según tipo de trabajo ...,2021,Argentina,Tiempo trabajo remunerado,"19,3"
2,Tiempo total de trabajo según tipo de trabajo ...,2021,Argentina,Tiempo trabajo no remunerado,"33,2"
3,Tiempo total de trabajo según tipo de trabajo ...,2021,Colombia,Tiempo total de trabajo,"51,0"
4,Tiempo total de trabajo según tipo de trabajo ...,2021,Colombia,Tiempo trabajo remunerado,"16,9"

In [20]:
# Convertimos la columna 'valor' a string, cambiamos coma por punto y convertimos a float
tiempo_trabajo_copia['promedio_horas_semanales'] = pd.to_numeric(
    tiempo_trabajo_copia['promedio_horas_semanales'].astype(str).str.replace(',', '.'), 
    errors='coerce'
)

# Mostrar resultados
display(tiempo_trabajo_copia[['promedio_horas_semanales']].head())
print(f"Nuevo tipo de dato: {tiempo_trabajo_copia['promedio_horas_semanales'].dtype}")

   promedio_horas_semanales
0                      52.5
1                      19.3
2                      33.2
3                      51.0
4                      16.9

Nuevo tipo de dato: float64

In [21]:
# Estandarización de la columna 'pais' para garantizar consistencia en la clave de unión.
# Se eliminan espacios, se unifica el formato en mayúsculas y se remueven acentos.
tiempo_trabajo_copia['pais'] = (
    tiempo_trabajo_copia['pais']
    .str.strip()
    .str.upper()
    .str.normalize('NFKD')
    .str.encode('ascii', errors='ignore')
    .str.decode('utf-8')
)

# Mostrar resultados
tiempo_trabajo_copia['pais'].unique()

array(['ARGENTINA', 'COLOMBIA', 'REPUBLICA DOMINICANA', 'COSTA RICA',
       'GUATEMALA', 'URUGUAY', 'CHILE', 'EL SALVADOR', 'PERU'],
      dtype=object)

In [22]:
# Cantidad de tipos de trabajo por país
tiempo_trabajo_copia.groupby("pais")["tipo_trabajo"].nunique()

pais
ARGENTINA               3
CHILE                   3
COLOMBIA                3
COSTA RICA              3
EL SALVADOR             3
GUATEMALA               3
PERU                    3
REPUBLICA DOMINICANA    3
URUGUAY                 3
Name: tipo_trabajo, dtype: int64

In [23]:
# Inspección del dataset intermedio
tiempo_trabajo_copia.head(10)

,indicador,anios,pais,tipo_trabajo,promedio_horas_semanales
0,Tiempo total de trabajo según tipo de trabajo ...,2021,ARGENTINA,Tiempo total de trabajo,52.5
1,Tiempo total de trabajo según tipo de trabajo ...,2021,ARGENTINA,Tiempo trabajo remunerado,19.3
2,Tiempo total de trabajo según tipo de trabajo ...,2021,ARGENTINA,Tiempo trabajo no remunerado,33.2
3,Tiempo total de trabajo según tipo de trabajo ...,2021,COLOMBIA,Tiempo total de trabajo,51.0
4,Tiempo total de trabajo según tipo de trabajo ...,2021,COLOMBIA,Tiempo trabajo remunerado,16.9
5,Tiempo total de trabajo según tipo de trabajo ...,2021,COLOMBIA,Tiempo trabajo no remunerado,34.1
6,Tiempo total de trabajo según tipo de trabajo ...,2021,REPUBLICA DOMINICANA,Tiempo total de trabajo,48.1
7,Tiempo total de trabajo según tipo de trabajo ...,2021,REPUBLICA DOMINICANA,Tiempo trabajo remunerado,22.6
8,Tiempo total de trabajo según tipo de trabajo ...,2021,REPUBLICA DOMINICANA,Tiempo trabajo no remunerado,25.5
9,Tiempo total de trabajo según tipo de trabajo ...,2022,COSTA RICA,Tiempo total de trabajo,53.8

In [24]:
# Transformación a formato ancho: cada tipo de trabajo pasa a ser una columna
# para obtener una única fila por país

df_tiempo_trabajo = tiempo_trabajo_copia.pivot(
    index='pais',
    columns='tipo_trabajo',
    values='promedio_horas_semanales'
).reset_index()

# Eliminación del nombre del eje de columnas para mayor claridad
df_tiempo_trabajo.columns.name = None

# Recuperación de columnas constantes por país (indicador y anios)
df_extra = tiempo_trabajo_copia[['pais', 'indicador', 'anios']].drop_duplicates()

df_tiempo_trabajo = df_tiempo_trabajo.merge(df_extra, on='pais', how='left')

# Limpieza de nombres de columnas
df_tiempo_trabajo = df_tiempo_trabajo.rename(
    columns=
    {'Tiempo total de trabajo': 'tiempo_total_trabajo',
    'Tiempo trabajo remunerado': 'tiempo_trabajo_remunerado',
    'Tiempo trabajo no remunerado': 'tiempo_trabajo_no_remunerado'
    }
)

# Aplicamos orden de columnas correcto
df_tiempo_trabajo = df_tiempo_trabajo[
    ['indicador', 'anios', 'pais', 'tiempo_total_trabajo', 'tiempo_trabajo_remunerado', 'tiempo_trabajo_no_remunerado']
]

# Verificación del resultado
df_tiempo_trabajo

,indicador,anios,pais,tiempo_total_trabajo,tiempo_trabajo_remunerado,tiempo_trabajo_no_remunerado
0,Tiempo total de trabajo según tipo de trabajo ...,2021,ARGENTINA,52.5,19.3,33.2
1,Tiempo total de trabajo según tipo de trabajo ...,2023,CHILE,54.0,18.4,35.6
2,Tiempo total de trabajo según tipo de trabajo ...,2021,COLOMBIA,51.0,16.9,34.1
3,Tiempo total de trabajo según tipo de trabajo ...,2022,COSTA RICA,53.8,18.6,35.2
4,Tiempo total de trabajo según tipo de trabajo ...,2022,EL SALVADOR,64.6,20.9,43.6
5,Tiempo total de trabajo según tipo de trabajo ...,2022,GUATEMALA,56.3,14.4,41.9
6,Tiempo total de trabajo según tipo de trabajo ...,2024,PERU,60.9,22.5,38.4
7,Tiempo total de trabajo según tipo de trabajo ...,2021,REPUBLICA DOMINICANA,48.1,22.6,25.5
8,Tiempo total de trabajo según tipo de trabajo ...,2022,URUGUAY,54.5,20.9,33.6

## 1\.3\. Dataset 3: "Estructura de la población por sexo y por grupos de edad \(Porcentaje\)"

## 1\.3\.1 Extracción y exploración del dataset

In [25]:
# Cargar el dataset
poblacion = pd.read_csv('/work/Poblacion por genero y edad.csv', encoding='latin-1')

# Mostrar todas las columnas
columnas = poblacion.columns.tolist()
print(columnas)

['indicator', 'País__ESTANDAR', 'Sexo', 'Grupos quinquenales de edad', 'Años__ESTANDAR', 'value', 'unit', 'notes_ids', 'source_id']

In [26]:
# Número total de filas y columnas del dataset
poblacion.shape

(378, 9)

In [27]:
# Comprobación de los tipos de datos
poblacion.dtypes

indicator                       object
País__ESTANDAR                  object
Sexo                            object
Grupos quinquenales de edad     object
Años__ESTANDAR                   int64
value                           object
unit                            object
notes_ids                      float64
source_id                        int64
dtype: object

In [28]:
# Verificación de valores nulos por columna
poblacion.isnull().sum()

indicator                        0
País__ESTANDAR                   0
Sexo                             0
Grupos quinquenales de edad      0
Años__ESTANDAR                   0
value                            0
unit                             0
notes_ids                      378
source_id                        0
dtype: int64

## 1\.3\.2 Transformación

In [29]:
# Se crea una copia sobre la cual realizar las transformaciones
poblacion_copia = poblacion.copy()

In [30]:
# Normalización de nombres de columnas para mejorar la legibilidad
poblacion_copia = poblacion_copia.rename(
    columns=
    {'indicator': 'indicador',
    'País__ESTANDAR': 'pais',
    'Grupos quinquenales de edad': 'grupos_edad',
    'Años__ESTANDAR': 'anios',
    'value': 'miles_personas_a_mitad_anio'
    }
)

# Mostrar el resultado
poblacion_copia.head(5)

,indicador,pais,Sexo,grupos_edad,anios,miles_personas_a_mitad_anio,unit,notes_ids,source_id
0,"Población, por grupos de edad, según sexo",Argentina,Mujeres,0-4,2020,"1676,5","Miles de personas, a mitad del año",NaN,6547
1,"Población, por grupos de edad, según sexo",Argentina,Mujeres,0-4,2025,"1515,9","Miles de personas, a mitad del año",NaN,6547
2,"Población, por grupos de edad, según sexo",Argentina,Mujeres,5-9,2020,"1784,0","Miles de personas, a mitad del año",NaN,6547
3,"Población, por grupos de edad, según sexo",Argentina,Mujeres,5-9,2025,"1674,9","Miles de personas, a mitad del año",NaN,6547
4,"Población, por grupos de edad, según sexo",Argentina,Mujeres,10-14,2020,"1720,8","Miles de personas, a mitad del año",NaN,6547

In [31]:
# Convertimos la columna 'valor' a string, cambiamos coma por punto y convertimos a float
poblacion_copia['miles_personas_a_mitad_anio'] = pd.to_numeric(
    poblacion_copia['miles_personas_a_mitad_anio'].astype(str).str.replace(',', '.'), 
    errors='coerce'
)

# Mostrar resultados
display(poblacion_copia[['miles_personas_a_mitad_anio']].head())
print(f"Nuevo tipo de dato: {poblacion_copia['miles_personas_a_mitad_anio'].dtype}")

   miles_personas_a_mitad_anio
0                       1676.5
1                       1515.9
2                       1784.0
3                       1674.9
4                       1720.8

Nuevo tipo de dato: float64

In [32]:
# Eliminación de columnas no significativas para el análisis
poblacion_copia = poblacion_copia.drop(
    columns=['Sexo', 'unit', 'notes_ids', 'source_id'],
    errors ='ignore'
)

# Mostrar el resultado
poblacion_copia.head(5)

,indicador,pais,grupos_edad,anios,miles_personas_a_mitad_anio
0,"Población, por grupos de edad, según sexo",Argentina,0-4,2020,1676.5
1,"Población, por grupos de edad, según sexo",Argentina,0-4,2025,1515.9
2,"Población, por grupos de edad, según sexo",Argentina,5-9,2020,1784.0
3,"Población, por grupos de edad, según sexo",Argentina,5-9,2025,1674.9
4,"Población, por grupos de edad, según sexo",Argentina,10-14,2020,1720.8

In [33]:
poblacion_copia.anios.unique()

array([2020, 2025])

In [34]:
# Creamos la referencia con el año más nuevo de cada país
referencia_max = poblacion_copia.groupby('pais', as_index=False)['anios'].max()

# Filtramos el dataset por el último año disponible por país
poblacion_filtrada = poblacion_copia.merge(
    referencia_max, 
    on=['pais', 'anios'], 
    how='inner'
)

# Verificamos el resultado
print(f"Filas originales: {len(poblacion_copia)}")
print(f"Filas filtradas: {len(poblacion_filtrada)}")
display(poblacion_filtrada.head(20))

Filas originales: 378
Filas filtradas: 189

,indicador,pais,grupos_edad,anios,miles_personas_a_mitad_anio
0,"Población, por grupos de edad, según sexo",Argentina,0-4,2025,1515.9
1,"Población, por grupos de edad, según sexo",Argentina,5-9,2025,1674.9
2,"Población, por grupos de edad, según sexo",Argentina,10-14,2025,1783.1
3,"Población, por grupos de edad, según sexo",Argentina,15-19,2025,1719.5
4,"Población, por grupos de edad, según sexo",Argentina,20-24,2025,1692.5
5,"Población, por grupos de edad, según sexo",Argentina,25-29,2025,1707.4
6,"Población, por grupos de edad, según sexo",Argentina,30-34,2025,1717.8
7,"Población, por grupos de edad, según sexo",Argentina,35-39,2025,1622.0
8,"Población, por grupos de edad, según sexo",Argentina,40-44,2025,1567.3
9,"Población, por grupos de edad, según sexo",Argentina,45-49,2025,1512.1
10,"Población, por grupos de edad, según sexo",Argentina,50-54,2025,1326.2
11,"Población, por grupos de edad, según sexo",Argentina,55-59,2025,1136.8
12,"Población, por grupos de edad, según sexo",Argentina,60-64,2025,1040.6
13,"Población, por grupos de edad, según sexo",Argentina,65-69,2025,943.9
14,"Población, por grupos de edad, según sexo",Argentina,70-74,2025,815.2
15,"Población, por grupos de edad, según sexo",Argentina,75-79,2025,652.5
16,"Población, por grupos de edad, según sexo",Argentina,80-84,2025,461.6
17,"Población, por grupos de edad, según sexo",Argentina,85-89,2025,283.2
18,"Población, por grupos de edad, según sexo",Argentina,90-94,2025,147.4
19,"Población, por grupos de edad, según sexo",Argentina,95-99,2025,56.1

In [35]:
# Estandarización de la columna 'pais' para garantizar consistencia en la clave de unión.
# Se eliminan espacios, se unifica el formato en mayúsculas y se remueven acentos.
poblacion_filtrada["pais"] = (
    poblacion_filtrada["pais"]
    .str.strip()
    .str.upper()
    .str.normalize('NFKD')
    .str.encode('ascii', errors='ignore')
    .str.decode('utf-8')
)

# Mostrar resultados
poblacion_filtrada['pais'].unique()

array(['ARGENTINA', 'CHILE', 'COLOMBIA', 'COSTA RICA', 'EL SALVADOR',
       'GUATEMALA', 'PERU', 'REPUBLICA DOMINICANA', 'URUGUAY'],
      dtype=object)

In [36]:
# Cantidad de grupos etarios por país
poblacion_filtrada.groupby("pais")["grupos_edad"].nunique()

pais
ARGENTINA               21
CHILE                   21
COLOMBIA                21
COSTA RICA              21
EL SALVADOR             21
GUATEMALA               21
PERU                    21
REPUBLICA DOMINICANA    21
URUGUAY                 21
Name: grupos_edad, dtype: int64

In [37]:
# Inspección del dataset intermedio
poblacion_filtrada.head(20)

,indicador,pais,grupos_edad,anios,miles_personas_a_mitad_anio
0,"Población, por grupos de edad, según sexo",ARGENTINA,0-4,2025,1515.9
1,"Población, por grupos de edad, según sexo",ARGENTINA,5-9,2025,1674.9
2,"Población, por grupos de edad, según sexo",ARGENTINA,10-14,2025,1783.1
3,"Población, por grupos de edad, según sexo",ARGENTINA,15-19,2025,1719.5
4,"Población, por grupos de edad, según sexo",ARGENTINA,20-24,2025,1692.5
5,"Población, por grupos de edad, según sexo",ARGENTINA,25-29,2025,1707.4
6,"Población, por grupos de edad, según sexo",ARGENTINA,30-34,2025,1717.8
7,"Población, por grupos de edad, según sexo",ARGENTINA,35-39,2025,1622.0
8,"Población, por grupos de edad, según sexo",ARGENTINA,40-44,2025,1567.3
9,"Población, por grupos de edad, según sexo",ARGENTINA,45-49,2025,1512.1
10,"Población, por grupos de edad, según sexo",ARGENTINA,50-54,2025,1326.2
11,"Población, por grupos de edad, según sexo",ARGENTINA,55-59,2025,1136.8
12,"Población, por grupos de edad, según sexo",ARGENTINA,60-64,2025,1040.6
13,"Población, por grupos de edad, según sexo",ARGENTINA,65-69,2025,943.9
14,"Población, por grupos de edad, según sexo",ARGENTINA,70-74,2025,815.2
15,"Población, por grupos de edad, según sexo",ARGENTINA,75-79,2025,652.5
16,"Población, por grupos de edad, según sexo",ARGENTINA,80-84,2025,461.6
17,"Población, por grupos de edad, según sexo",ARGENTINA,85-89,2025,283.2
18,"Población, por grupos de edad, según sexo",ARGENTINA,90-94,2025,147.4
19,"Población, por grupos de edad, según sexo",ARGENTINA,95-99,2025,56.1

## 1\.4\. Consolidación de dataset de análisis

In [38]:
# Detección de países que no coinciden entre fuentes antes del merge
p1 = set(poblacion_filtrada["pais"])
p2 = set(df_tiempo_trabajo["pais"])
p3 = set(resultado_final["pais"])

print("Solo en población:", p1 - p2 - p3)
print("Solo en tiempo:", p2 - p1 - p3)
print("Solo en internet:", p3 - p1 - p2)

Solo en población: set()
Solo en tiempo: set()
Solo en internet: set()

In [39]:
# Copias para el merge final (no se modifican los datasets del ETL)
df_poblacion = poblacion_filtrada.copy()
df_tiempo = df_tiempo_trabajo.copy()
df_internet = resultado_final.copy()

# Eliminación de columnas innecesarias SÓLO para la fase de merge
df_poblacion = df_poblacion.drop(columns=["indicador"])
df_tiempo = df_tiempo.drop(columns=["indicador", "anios"])
df_internet = df_internet.drop(columns=["edad", "anio"])

# ---------------------------------------------------
# DATASET 1: TIEMPO + INTERNET (nivel país)
# ---------------------------------------------------
df_tiempo_internet = df_tiempo.merge(df_internet, on="pais", how="left")
df_tiempo_internet.to_csv('/work/Trabajo_Remunerado_DATA4CCION/data/df_tiempo_internet.csv', index=False)

# ---------------------------------------------------
# DATASET 2: POBLACIÓN (nivel país + edad + cantidad de personas)
# ---------------------------------------------------
orden_edades = [
    "0-4", "5-9", "10-14", "15-19", "20-24",
    "25-29", "30-34", "35-39", "40-44", "45-49",
    "50-54", "55-59", "60-64", "65-69", "70-74",
    "75-79", "80-84", "85-89", "90-94", "95-99",
    "100 y más"
]

df_poblacion["grupos_edad"] = pd.Categorical(
    df_poblacion["grupos_edad"],
    categories=orden_edades,
    ordered=True
)

df_poblacion = df_poblacion.sort_values(by=["pais", "grupos_edad"])
df_poblacion.to_csv('/work/Trabajo_Remunerado_DATA4CCION/data/df_poblacion.csv', index=False)

In [40]:
df_tiempo_internet.head(10)

,pais,tiempo_total_trabajo,tiempo_trabajo_remunerado,tiempo_trabajo_no_remunerado,porcentaje_uso_internet
0,ARGENTINA,52.5,19.3,33.2,89.1403
1,CHILE,54.0,18.4,35.6,94.4025
2,COLOMBIA,51.0,16.9,34.1,78.2038
3,COSTA RICA,53.8,18.6,35.2,85.8248
4,EL SALVADOR,64.6,20.9,43.6,52.3743
5,GUATEMALA,56.3,14.4,41.9,48.5503
6,PERU,60.9,22.5,38.4,80.2250
7,REPUBLICA DOMINICANA,48.1,22.6,25.5,91.2981
8,URUGUAY,54.5,20.9,33.6,92.4471

In [41]:
df_poblacion.head(10)

        pais grupos_edad  anios  miles_personas_a_mitad_anio
0  ARGENTINA         0-4   2025                       1515.9
1  ARGENTINA         5-9   2025                       1674.9
2  ARGENTINA       10-14   2025                       1783.1
3  ARGENTINA       15-19   2025                       1719.5
4  ARGENTINA       20-24   2025                       1692.5
5  ARGENTINA       25-29   2025                       1707.4
6  ARGENTINA       30-34   2025                       1717.8
7  ARGENTINA       35-39   2025                       1622.0
8  ARGENTINA       40-44   2025                       1567.3
9  ARGENTINA       45-49   2025                       1512.1

In [42]:
df_tiempo_internet.dtypes

pais                             object
tiempo_total_trabajo            float64
tiempo_trabajo_remunerado       float64
tiempo_trabajo_no_remunerado    float64
porcentaje_uso_internet         float64
dtype: object

In [43]:
df_poblacion.dtypes

pais                             object
grupos_edad                    category
anios                             int64
miles_personas_a_mitad_anio     float64
dtype: object

In [44]:
df_poblacion

          pais grupos_edad  anios  miles_personas_a_mitad_anio
0    ARGENTINA         0-4   2025                       1515.9
1    ARGENTINA         5-9   2025                       1674.9
2    ARGENTINA       10-14   2025                       1783.1
3    ARGENTINA       15-19   2025                       1719.5
4    ARGENTINA       20-24   2025                       1692.5
..         ...         ...    ...                          ...
184    URUGUAY       80-84   2025                         47.7
185    URUGUAY       85-89   2025                         34.0
186    URUGUAY       90-94   2025                         20.4
187    URUGUAY       95-99   2025                          9.1
188    URUGUAY   100 y más   2025                          3.2

[189 rows x 4 columns]

# 2\. Análisis Exploratorio de Datos \(EDA\)

En esta etapa realizamos un análisis exploratorio del dataset con el objetivo de comprender la estructura de los datos y preparar la información para la construcción del mapa interactivo\.

El EDA se enfoca en tres ejes principales:

\- Distribución poblacional femenina por país en edad activa, para identificar dónde se concentra la población con mayor potencial de participación en el trabajo remunerado\.
\- Carga de trabajo \(remunerado y no remunerado\), con especial énfasis en la proporción de trabajo no remunerado como indicador de carga de cuidados\.
\- Brecha digital, analizando el nivel de uso de internet como aproximación al acceso a conectividad\.

A partir de estos ejes, se construyen indicadores que permiten resumir la información:

\- Carga de cuidados  
\- Brecha digital  
\- Vulnerabilidad estructural  
\- Peso poblacional en edad activa  
\- Impacto total

El objetivo del EDA es identificar patrones entre países y generar los insumos necesarios para el desarrollo del índice y el mapa interactivo final\.

## 2\.1\. Carga de cuidados

Mide la proporción del tiempo total de trabajo femenino que se destina a trabajo no remunerado \(cuidados y tareas domésticas\)\.

Cálculo: tiempo de trabajo no remunerado / tiempo total de trabajo

In [45]:
import numpy as np

df_tiempo_internet["carga_cuidados"] = (
    df_tiempo_internet["tiempo_trabajo_no_remunerado"] /
    df_tiempo_internet["tiempo_total_trabajo"].replace(0, np.nan)
) * 100

In [46]:
# Revisamos las primeras filas
df_tiempo_internet[
    ["pais",
    "tiempo_total_trabajo", "tiempo_trabajo_no_remunerado",
    "carga_cuidados"]
].head(10)

,pais,tiempo_total_trabajo,tiempo_trabajo_no_remunerado,carga_cuidados
0,ARGENTINA,52.5,33.2,63.238095
1,CHILE,54.0,35.6,65.925926
2,COLOMBIA,51.0,34.1,66.862745
3,COSTA RICA,53.8,35.2,65.427509
4,EL SALVADOR,64.6,43.6,67.492260
5,GUATEMALA,56.3,41.9,74.422735
6,PERU,60.9,38.4,63.054187
7,REPUBLICA DOMINICANA,48.1,25.5,53.014553
8,URUGUAY,54.5,33.6,61.651376

In [47]:
# Obtenemos un resumen general
df_tiempo_internet["carga_cuidados"].describe()

count     9.000000
mean     64.565487
std       5.696103
min      53.014553
25%      63.054187
50%      65.427509
75%      66.862745
max      74.422735
Name: carga_cuidados, dtype: float64

In [48]:
# Ranking de carga de cuidados por país en mujeres
df_tiempo_internet[["pais", "carga_cuidados"]].sort_values(
    by="carga_cuidados",
    ascending=False
)

                   pais  carga_cuidados
5             GUATEMALA       74.422735
4           EL SALVADOR       67.492260
2              COLOMBIA       66.862745
1                 CHILE       65.925926
3            COSTA RICA       65.427509
0             ARGENTINA       63.238095
6                  PERU       63.054187
8               URUGUAY       61.651376
7  REPUBLICA DOMINICANA       53.014553

Conclusión preliminar: Observamos que Guatemala es el país, dentro de la muestra analizada, donde las mujeres presentan una mayor carga de cuidados, dedicando un 74\.42% de su tiempo de trabajo a tareas no remuneradas\. Le sigue El Salvador con un 67\.49%\.

## 2\.2\. Brecha digital

Mide el nivel de acceso faltante a internet en la población femenina, como aproximación a la brecha de conectividad digital\. Los valores más altos indican menor nivel de acceso y mayor brecha digital\. Por ejemplo, si el 70% de la población usa internet, la brecha digital es del 30%\.

Cálculo: 100 \- % uso de internet

In [49]:
df_tiempo_internet["brecha_digital"] = 100 - df_tiempo_internet["porcentaje_uso_internet"]

In [50]:
# Revisamos las primeras filas
df_tiempo_internet[["pais", "porcentaje_uso_internet", "brecha_digital"]].head(10)

                   pais  porcentaje_uso_internet  brecha_digital
0             ARGENTINA                  89.1403         10.8597
1                 CHILE                  94.4025          5.5975
2              COLOMBIA                  78.2038         21.7962
3            COSTA RICA                  85.8248         14.1752
4           EL SALVADOR                  52.3743         47.6257
5             GUATEMALA                  48.5503         51.4497
6                  PERU                  80.2250         19.7750
7  REPUBLICA DOMINICANA                  91.2981          8.7019
8               URUGUAY                  92.4471          7.5529

In [51]:
# Ranking de uso de internet por país en mujeres
df_tiempo_internet[["pais", "brecha_digital"]].sort_values(
    by="brecha_digital",
    ascending=False
)

                   pais  brecha_digital
5             GUATEMALA         51.4497
4           EL SALVADOR         47.6257
2              COLOMBIA         21.7962
6                  PERU         19.7750
3            COSTA RICA         14.1752
0             ARGENTINA         10.8597
7  REPUBLICA DOMINICANA          8.7019
8               URUGUAY          7.5529
1                 CHILE          5.5975

Conclusión preliminar: Se observa una tendencia en la que Guatemala y El Salvador presentan simultáneamente mayor carga de cuidados y menor acceso a internet \(51\.45% y 47\.62%, respectivamente\) dentro de la muestra analizada, lo que sugiere posibles contextos de mayor vulnerabilidad relativa\.

## 2\.3\. Vulnerabilidad estructural

Mide la combinación de carga de cuidados y brecha digital, como un indicador agregado del nivel de vulnerabilidad estructural\. Este es el índice combinado del proyecto, que integra ambas variables en un puntaje de riesgo para identificar los contextos más críticos por país\.

Cálculo: \(carga de cuidados \+ brecha digital\) / 2
Es decir, se calcula el valor medio entre ambos problemas\. Los valores más altos indican mayor vulnerabilidad estructural, al combinar mayor carga de cuidados y menor acceso digital\.

In [52]:
df_tiempo_internet["vulnerabilidad"] = (
    df_tiempo_internet["carga_cuidados"] + df_tiempo_internet["brecha_digital"]
) / 2

In [53]:
# Revisamos las primeras filas
df_tiempo_internet[["pais", "carga_cuidados", "brecha_digital", "vulnerabilidad"]].head(10)

                   pais  carga_cuidados  brecha_digital  vulnerabilidad
0             ARGENTINA       63.238095         10.8597       37.048898
1                 CHILE       65.925926          5.5975       35.761713
2              COLOMBIA       66.862745         21.7962       44.329473
3            COSTA RICA       65.427509         14.1752       39.801355
4           EL SALVADOR       67.492260         47.6257       57.558980
5             GUATEMALA       74.422735         51.4497       62.936218
6                  PERU       63.054187         19.7750       41.414594
7  REPUBLICA DOMINICANA       53.014553          8.7019       30.858227
8               URUGUAY       61.651376          7.5529       34.602138

In [54]:
# Ranking de vulnerabilidad estructural por país
df_tiempo_internet[["pais", "vulnerabilidad"]].sort_values(
    by="vulnerabilidad",
    ascending=False
)

                   pais  vulnerabilidad
5             GUATEMALA       62.936218
4           EL SALVADOR       57.558980
2              COLOMBIA       44.329473
6                  PERU       41.414594
3            COSTA RICA       39.801355
0             ARGENTINA       37.048898
1                 CHILE       35.761713
8               URUGUAY       34.602138
7  REPUBLICA DOMINICANA       30.858227

Conclusión preliminar: Los resultados de este índice combinado refuerzan, a nivel general, las conclusiones preliminares obtenidas en los análisis previos, evidenciando patrones consistentes entre carga de cuidados y brecha digital\. En conjunto, este indicador permite sintetizar en una sola medida dos dimensiones estructurales clave del problema, facilitando la comparación entre países y la identificación de tendencias generales dentro de la muestra\. Asimismo, resulta clave para identificar contextos prioritarios de intervención, ya que permite reconocer los países con situaciones más críticas en términos de vulnerabilidad estructural\.

In [55]:
df_tiempo_internet

,pais,tiempo_total_trabajo,tiempo_trabajo_remunerado,tiempo_trabajo_no_remunerado,porcentaje_uso_internet,carga_cuidados,brecha_digital,vulnerabilidad
0,ARGENTINA,52.5,19.3,33.2,89.1403,63.238095,10.8597,37.048898
1,CHILE,54.0,18.4,35.6,94.4025,65.925926,5.5975,35.761713
2,COLOMBIA,51.0,16.9,34.1,78.2038,66.862745,21.7962,44.329473
3,COSTA RICA,53.8,18.6,35.2,85.8248,65.427509,14.1752,39.801355
4,EL SALVADOR,64.6,20.9,43.6,52.3743,67.492260,47.6257,57.558980
5,GUATEMALA,56.3,14.4,41.9,48.5503,74.422735,51.4497,62.936218
6,PERU,60.9,22.5,38.4,80.2250,63.054187,19.7750,41.414594
7,REPUBLICA DOMINICANA,48.1,22.6,25.5,91.2981,53.014553,8.7019,30.858227
8,URUGUAY,54.5,20.9,33.6,92.4471,61.651376,7.5529,34.602138

## 2\.4\. Peso poblacional \(edad activa\)

Calcula la proporción de mujeres en edad activa en cada país, como aproximación al volumen de población potencialmente expuesta a las condiciones de trabajo y brecha digital\. Este indicador se incorpora para dimensionar la magnitud real del problema en cada país, ya que no solo importa la intensidad de la vulnerabilidad estructural, sino también qué porcentaje de mujeres en la edad mencionada se ven afectadas\. De este modo, permite contextualizar el impacto potencial de las condiciones analizadas y aportar una mirada de escala poblacional al análisis\.

La elección del rango etario 15–64 no implica que el resto de los grupos no sea relevante, sino que responde al recorte analítico del proyecto, el cual se enmarca dentro de la categoría “trabajo remunerado”\. En este sentido, se prioriza la denominada “población en edad de trabajar”, definida por la OECD \(Organización para la Cooperación y el Desarrollo Económico\) como la proporción de personas entre 15 y 64 años respecto del total de la población\.

Cálculo: \(suma de miles de personas en los grupos de edad 15–64\) / total de mujeres del país

Los valores más altos indican una mayor proporción de mujeres en edad activa dentro del país\.

In [56]:
# Filtramos el dataset y sólo dejamos las filas correspondientes al grupo etario de 15-64 años
df_activa = df_poblacion[df_poblacion["grupos_edad"].isin([
    "15-19","20-24","25-29","30-34","35-39",
    "40-44","45-49","50-54","55-59","60-64"
])]

# Cálculo de población total por país (todas las edades)
pob_total = df_poblacion.groupby("pais")["miles_personas_a_mitad_anio"].sum()

# Cálculo de población en edad activa por país
pob_activa = df_activa.groupby("pais")["miles_personas_a_mitad_anio"].sum()

# Cálculo del peso poblacional de la edad activa
peso_poblacional_edad_activa = (pob_activa / pob_total) * 100

In [57]:
# Ranking de países de mayor a menor proporción de mujeres en edad activa
peso_poblacional_edad_activa.sort_values(ascending=False)

pais
COLOMBIA                68.778213
COSTA RICA              68.393371
EL SALVADOR             67.341727
CHILE                   66.966095
PERU                    66.050175
REPUBLICA DOMINICANA    65.329881
GUATEMALA               64.329492
ARGENTINA               64.311764
URUGUAY                 63.819409
Name: miles_personas_a_mitad_anio, dtype: float64

Conclusión preliminar: Se observa una distribución relativamente homogénea de la población femenina en edad activa entre los países analizados, con variaciones acotadas entre el 63% y el 68%, lo que sugiere que las diferencias en el impacto del índice estarán principalmente determinadas por el grado de vulnerabilidad estructural y no por la composición demográfica\.
No obstante, se trata en todos los casos de más de la mitad de la población femenina, lo que refuerza la relevancia de considerar este aspecto en el análisis de la problemática\.

## 2\.5\. Riesgo poblacional

El riesgo poblacional permite identificar qué países concentran mayor nivel de criticidad dentro del análisis, combinando la vulnerabilidad estructural con el peso de la población en edad activa\. De esta manera, no solo se considera la intensidad de las condiciones de desigualdad en términos de carga de cuidados y brecha digital, sino también cuántas mujeres están potencialmente expuestas a estas condiciones en cada país\.

Cálculo: vulnerabilidad estructural \* proporción de población en edad activa

Esto permite obtener una medida integrada del impacto potencial del problema en cada contexto nacional\. En este sentido, valores más altos indican países donde la combinación entre condiciones estructurales adversas y mayor exposición poblacional en edad activa genera escenarios más críticos, lo que resulta clave para la identificación de prioridades de intervención\.

In [58]:
# ---------------------------------------------------
# DATASET DE RIESGO POBLACIONAL (NIVEL PAÍS)
# ---------------------------------------------------

# Partimos del dataset de indicadores a nivel país
df_riesgo = df_tiempo_internet[["pais", "vulnerabilidad"]].copy()

# Agregamos el peso poblacional de la edad activa
# (proporción de mujeres en edad 15-64 dentro del total)
df_riesgo = df_riesgo.merge(
    peso_poblacional_edad_activa.rename("peso_poblacional_edad_activa"),
    on="pais",
    how="left"
)

# Cálculo del riesgo poblacional:
# combinación de vulnerabilidad estructural y peso poblacional
df_riesgo["riesgo_poblacional"] = (
    df_riesgo["vulnerabilidad"] * df_riesgo["peso_poblacional_edad_activa"]
) / 100

In [59]:
# Ranking de riesgo poblacional

df_riesgo = df_riesgo.sort_values(
    by="riesgo_poblacional",
    ascending=False
)

df_riesgo

,pais,vulnerabilidad,peso_poblacional_edad_activa,riesgo_poblacional
5,GUATEMALA,62.936218,64.329492,40.486549
4,EL SALVADOR,57.558980,67.341727,38.761211
2,COLOMBIA,44.329473,68.778213,30.489019
6,PERU,41.414594,66.050175,27.354412
3,COSTA RICA,39.801355,68.393371,27.221488
1,CHILE,35.761713,66.966095,23.948223
0,ARGENTINA,37.048898,64.311764,23.826800
8,URUGUAY,34.602138,63.819409,22.082880
7,REPUBLICA DOMINICANA,30.858227,65.329881,20.159643

Conclusión preliminar: Se observa que Guatemala lidera el ranking de riesgo poblacional, seguido por El Salvador\. Esto indica que, dentro de la muestra analizada, estos países no solo presentan mayores niveles de vulnerabilidad estructural, sino que además dicha situación se ve amplificada por el peso relativo de su población en edad activa\. En conjunto, estos resultados refuerzan la identificación de estos países como los contextos más críticos dentro del análisis, al concentrar simultáneamente mayor intensidad de desigualdades y mayor exposición poblacional\.

In [60]:
df_riesgo.to_csv('/work/Trabajo_Remunerado_DATA4CCION/data/df_riesgo.csv', index=False)
df_riesgo

,pais,vulnerabilidad,peso_poblacional_edad_activa,riesgo_poblacional
5,GUATEMALA,62.936218,64.329492,40.486549
4,EL SALVADOR,57.558980,67.341727,38.761211
2,COLOMBIA,44.329473,68.778213,30.489019
6,PERU,41.414594,66.050175,27.354412
3,COSTA RICA,39.801355,68.393371,27.221488
1,CHILE,35.761713,66.966095,23.948223
0,ARGENTINA,37.048898,64.311764,23.826800
8,URUGUAY,34.602138,63.819409,22.082880
7,REPUBLICA DOMINICANA,30.858227,65.329881,20.159643

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=834e7868-2378-4c17-9544-b944164a7420' target="_blank">
<img alt='Created in deepnote.com' style='display:inline;max-height:16px;margin:0px;margin-right:7.5px;' src='' />
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>